module Test.Main where

-- import Prelude
-- import Control.Monad.Eff (Eff)
-- import Control.Monad.Eff.Console (CONSOLE)
-- import Control.Monad.Aff.AVar (AVAR)
-- 
-- --import Test.Unit.Main (runTest)
-- import Test.Unit.Main (run, runTestWith)
-- import Test.Unit.Output.TAP (runTest)
-- import Test.Unit.Console (TESTOUTPUT)
-- 
-- import Test.Data (dataSuite)
-- 
-- main :: forall e. Eff ( console :: CONSOLE
--                       , testOutput :: TESTOUTPUT
--                       , avar :: AVAR
--                       | e )
--                       Unit
-- main = run $ runTestWith runTest do
--   dataSuite
