OUTFILE:=static/out.js

deps := prelude maybe monoid arrays eff foldable-traversable newtype \
  generics lists transformers integers dom canvas refs localstorage \
  jquery
dev-deps := psci-support

all:
	pulp build -O | closure-compiler -O SIMPLE > $(OUTFILE)

# init and clean targets work on a project that is fully set up. init
# install all dependencies mentioned in bower.json, and clean removes
# all temporary files generated by psc.
.PHONY: init clean
init:
	bower install

clean:
	$(RM) -rf bower_components output $(OUTFILE)

# dist-init and dist-clean are meant for settings project from scratch.
# before calling dist-init make sure you've removed all entries from
# dependencies and devDependencies in bower.json. dist-clean doesn't
# do this yet.
.PHONY: dist-init dist-clean
dist-init:
	bower install --save $(addprefix purescript-, $(deps))
	bower install --save-dev $(addprefix purescript-, $(dev-deps))

dist-clean: clean
	$(RM) -rf .psci_modules .pulp-cache
