var PS={};(function(a){a.arrayMap=function(a){return function(c){for(var d=c.length,f=Array(d),e=0;e<d;e++)f[e]=a(c[e]);return f}}})(PS["Data.Functor"]=PS["Data.Functor"]||{});(function(a){var b=function(a){this.compose=a},c=new b(function(a){return function(b){return function(c){return a(b(c))}}});a.Semigroupoid=b;a.compose=function(a){return a.compose};a.semigroupoidFn=c})(PS["Control.Semigroupoid"]=PS["Control.Semigroupoid"]||{});
(function(a){var b=PS["Control.Semigroupoid"],c=function(a,b){this["__superclass_Control.Semigroupoid.Semigroupoid_0"]=a;this.id=b},d=new c(function(){return b.semigroupoidFn},function(a){return a});a.Category=c;a.id=function(a){return a.id};a.categoryFn=d})(PS["Control.Category"]=PS["Control.Category"]||{});
(function(a){a.apply=function(a){return function(c){return a(c)}};a["const"]=function(a){return function(c){return a}};a.flip=function(a){return function(c){return function(d){return a(d)(c)}}}})(PS["Data.Function"]=PS["Data.Function"]||{});(function(a){a.unit={}})(PS["Data.Unit"]=PS["Data.Unit"]||{});
(function(a){a.showIntImpl=function(a){return a.toString()};a.showNumberImpl=function(a){a=a.toString();return isNaN(a+".0")?a:a+".0"};a.showStringImpl=function(a){var c=a.length;return'"'+a.replace(/[\0-\x1F\x7F"\\]/g,function(d,f){switch(d){case '"':case "\\":return"\\"+d;case "\u0007":return"\\a";case "\b":return"\\b";case "\f":return"\\f";case "\n":return"\\n";case "\r":return"\\r";case "\t":return"\\t";case "\v":return"\\v"}var e=f+1,e=e<c&&"0"<=a[e]&&"9">=a[e]?"\\&":"";return"\\"+d.charCodeAt(0).toString(10)+
e})+'"'}})(PS["Data.Show"]=PS["Data.Show"]||{});(function(a){var b=PS["Data.Show"],c=function(a){this.show=a},d=new c(b.showStringImpl),f=new c(b.showNumberImpl),b=new c(b.showIntImpl);a.Show=c;a.show=function(a){return a.show};a.showInt=b;a.showNumber=f;a.showString=d})(PS["Data.Show"]=PS["Data.Show"]||{});(function(a){a.unit=PS["Data.Unit"].unit})(PS["Data.Unit"]=PS["Data.Unit"]||{});
(function(a){var b=PS["Data.Functor"],c=PS["Data.Function"],d=PS["Data.Unit"],f=PS["Control.Semigroupoid"],e=function(a){this.map=a},f=new e(f.compose(f.semigroupoidFn)),b=new e(b.arrayMap);a.Functor=e;a.map=function(a){return a.map};a.mapFlipped=function(a){return function(b){return function(c){return(0,a.map)(c)(b)}}};a["void"]=function(a){return(0,a.map)(c["const"](d.unit))};a.functorFn=f;a.functorArray=b})(PS["Data.Functor"]=PS["Data.Functor"]||{});
(function(a){a.concatArray=function(a){return function(c){return a.concat(c)}}})(PS["Data.Semigroup"]=PS["Data.Semigroup"]||{});(function(a){var b=function(a){this.append=a},c=new b(PS["Data.Semigroup"].concatArray);a.Semigroup=b;a.append=function(a){return a.append};a.semigroupArray=c})(PS["Data.Semigroup"]=PS["Data.Semigroup"]||{});(function(a){a.Alt=function(a,c){this["__superclass_Data.Functor.Functor_0"]=a;this.alt=c};a.alt=function(a){return a.alt}})(PS["Control.Alt"]=PS["Control.Alt"]||{});
(function(a){a.arrayApply=function(a){return function(c){for(var d=[],f=0,e=0,g=a.length;e<g;e++)for(var k=0,h=c.length;k<h;k++)d[f++]=a[e](c[k]);return d}}})(PS["Control.Apply"]=PS["Control.Apply"]||{});
(function(a){var b=PS["Data.Functor"],c=PS["Data.Function"],d=PS["Control.Category"],f=function(a,b){this["__superclass_Data.Functor.Functor_0"]=a;this.apply=b},e=new f(function(){return b.functorArray},PS["Control.Apply"].arrayApply);a.Apply=f;a.apply=function(a){return a.apply};a.applySecond=function(a){return function(e){return function(f){return(0,a.apply)(b.map(a["__superclass_Data.Functor.Functor_0"]())(c["const"](d.id(d.categoryFn)))(e))(f)}}};a.applyArray=e})(PS["Control.Apply"]=PS["Control.Apply"]||
{});
(function(a){var b=PS["Control.Apply"],c=PS["Data.Unit"];a.Applicative=function(a,b){this["__superclass_Control.Apply.Apply_0"]=a;this.pure=b};a.liftA1=function(a){return function(c){return function(e){return b.apply(a["__superclass_Control.Apply.Apply_0"]())((0,a.pure)(c))(e)}}};a.pure=function(a){return a.pure};a.unless=function(a){return function(b){return function(e){if(!b)return e;if(b)return(0,a.pure)(c.unit);throw Error("Failed pattern match at Control.Applicative line 63, column 1 - line 63, column 19: "+[b.constructor.name,
e.constructor.name]);}}};a.when=function(a){return function(b){return function(e){if(b)return e;if(!b)return(0,a.pure)(c.unit);throw Error("Failed pattern match at Control.Applicative line 58, column 1 - line 58, column 16: "+[b.constructor.name,e.constructor.name]);}}}})(PS["Control.Applicative"]=PS["Control.Applicative"]||{});(function(a){a.Plus=function(a,c){this["__superclass_Control.Alt.Alt_0"]=a;this.empty=c};a.empty=function(a){return a.empty}})(PS["Control.Plus"]=PS["Control.Plus"]||{});
(function(a){a.Alternative=function(a,c){this["__superclass_Control.Applicative.Applicative_0"]=a;this["__superclass_Control.Plus.Plus_1"]=c}})(PS["Control.Alternative"]=PS["Control.Alternative"]||{});(function(a){a.arrayBind=function(a){return function(c){for(var d=[],f=0,e=a.length;f<e;f++)Array.prototype.push.apply(d,c(a[f]));return d}}})(PS["Control.Bind"]=PS["Control.Bind"]||{});
(function(a){var b=PS["Control.Apply"],c=function(a,b){this["__superclass_Control.Apply.Apply_0"]=a;this.bind=b},d=new c(function(){return b.applyArray},PS["Control.Bind"].arrayBind);a.Bind=c;a.bind=function(a){return a.bind};a.bindArray=d})(PS["Control.Bind"]=PS["Control.Bind"]||{});
(function(a){var b=PS["Control.Applicative"],c=PS["Control.Bind"];a.Monad=function(a,b){this["__superclass_Control.Applicative.Applicative_0"]=a;this["__superclass_Control.Bind.Bind_1"]=b};a.ap=function(a){return function(f){return function(e){return c.bind(a["__superclass_Control.Bind.Bind_1"]())(f)(function(f){return c.bind(a["__superclass_Control.Bind.Bind_1"]())(e)(function(c){return b.pure(a["__superclass_Control.Applicative.Applicative_0"]())(f(c))})})}}}})(PS["Control.Monad"]=PS["Control.Monad"]||
{});(function(a){a.pureE=function(a){return function(){return a}};a.bindE=function(a){return function(c){return function(){return c(a())()}}}})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){var b=PS["Control.Monad.Eff"],c=PS["Control.Applicative"],d=PS["Control.Apply"],f=PS["Control.Bind"],e=PS["Control.Monad"],g=PS["Data.Functor"],k=new e.Monad(function(){return n},function(){return h}),h=new f.Bind(function(){return l},b.bindE),l=new d.Apply(function(){return q},e.ap(k)),n=new c.Applicative(function(){return l},b.pureE),q=new g.Functor(c.liftA1(n));a.functorEff=q;a.applyEff=l;a.applicativeEff=n;a.bindEff=h;a.monadEff=k})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||
{});(function(a){a.log=function(a){return function(){console.log(a);return{}}}})(PS["Control.Monad.Eff.Console"]=PS["Control.Monad.Eff.Console"]||{});(function(a){a.log=PS["Control.Monad.Eff.Console"].log})(PS["Control.Monad.Eff.Console"]=PS["Control.Monad.Eff.Console"]||{});
(function(a){a.select=function(a){return function(){return jQuery(a)}};a.getValue=function(a){return function(){return a.val()}};a.on=function(a){return function(c){return function(d){return function(){d.on(a,function(a){c(a)(jQuery(this))()})}}}};a.preventDefault=function(a){return function(){a.preventDefault()}}})(PS["Control.Monad.Eff.JQuery"]=PS["Control.Monad.Eff.JQuery"]||{});
(function(a){a.unsafeFromForeign=function(a){return a};a.tagOf=function(a){return Object.prototype.toString.call(a).slice(8,-1)}})(PS["Data.Foreign"]=PS["Data.Foreign"]||{});(function(a){var b=PS["Control.Category"];a.Bifunctor=function(a){this.bimap=a};a.bimap=function(a){return a.bimap};a.lmap=function(a){return function(d){return(0,a.bimap)(d)(b.id(b.categoryFn))}}})(PS["Data.Bifunctor"]=PS["Data.Bifunctor"]||{});
(function(a){a.topInt=2147483647;a.bottomInt=-2147483648})(PS["Data.Bounded"]=PS["Data.Bounded"]||{});(function(a){a.refEq=function(a){return function(c){return a===c}}})(PS["Data.Eq"]=PS["Data.Eq"]||{});(function(a){var b=PS["Data.Eq"],c=function(a){this.eq=a},d=new c(b.refEq),f=new c(b.refEq),b=new c(b.refEq);a.Eq=c;a.eq=function(a){return a.eq};a.eqBoolean=b;a.eqInt=f;a.eqNumber=d})(PS["Data.Eq"]=PS["Data.Eq"]||{});
(function(a){a.unsafeCompareImpl=function(a){return function(c){return function(d){return function(f){return function(e){return f<e?a:f>e?d:c}}}}}})(PS["Data.Ord.Unsafe"]=PS["Data.Ord.Unsafe"]||{});
(function(a){var b=PS["Data.Eq"],c=function(){function a(){}a.value=new a;return a}(),d=function(){function a(){}a.value=new a;return a}(),f=function(){function a(){}a.value=new a;return a}(),b=new b.Eq(function(a){return function(b){return a instanceof c&&b instanceof c||a instanceof d&&b instanceof d||a instanceof f&&b instanceof f?!0:!1}});a.LT=c;a.GT=d;a.EQ=f;a.eqOrdering=b})(PS["Data.Ordering"]=PS["Data.Ordering"]||{});
(function(a){var b=PS["Data.Ordering"],b=PS["Data.Ord.Unsafe"].unsafeCompareImpl(b.LT.value)(b.EQ.value)(b.GT.value);a.unsafeCompare=b})(PS["Data.Ord.Unsafe"]=PS["Data.Ord.Unsafe"]||{});(function(a){a.intSub=function(a){return function(c){return a-c|0}};a.numSub=function(a){return function(c){return a-c}}})(PS["Data.Ring"]=PS["Data.Ring"]||{});
(function(a){a.intAdd=function(a){return function(c){return a+c|0}};a.intMul=function(a){return function(c){return a*c|0}};a.numAdd=function(a){return function(c){return a+c}};a.numMul=function(a){return function(c){return a*c}}})(PS["Data.Semiring"]=PS["Data.Semiring"]||{});
(function(a){var b=PS["Data.Semiring"],c=function(a,b,c,d){this.add=a;this.mul=b;this.one=c;this.zero=d},d=new c(b.numAdd,b.numMul,1,0),b=new c(b.intAdd,b.intMul,1,0);a.Semiring=c;a.add=function(a){return a.add};a.mul=function(a){return a.mul};a.one=function(a){return a.one};a.zero=function(a){return a.zero};a.semiringInt=b;a.semiringNumber=d})(PS["Data.Semiring"]=PS["Data.Semiring"]||{});
(function(a){var b=PS["Data.Ring"],c=PS["Data.Semiring"],d=function(a,b){this["__superclass_Data.Semiring.Semiring_0"]=a;this.sub=b},f=new d(function(){return c.semiringNumber},b.numSub),b=new d(function(){return c.semiringInt},b.intSub);a.Ring=d;a.negate=function(a){return function(b){return(0,a.sub)(c.zero(a["__superclass_Data.Semiring.Semiring_0"]()))(b)}};a.sub=function(a){return a.sub};a.ringInt=b;a.ringNumber=f})(PS["Data.Ring"]=PS["Data.Ring"]||{});
(function(a){var b=PS["Data.Eq"],c=PS["Data.Ord.Unsafe"],d=PS["Data.Ordering"],f=PS["Data.Ring"],e=PS["Data.Semiring"],g=function(a,b){this["__superclass_Data.Eq.Eq_0"]=a;this.compare=b},k=new g(function(){return b.eqNumber},c.unsafeCompare),c=new g(function(){return b.eqInt},c.unsafeCompare),h=function(a){return function(b){return function(c){return(0,a.compare)(b)(c)instanceof d.LT?!1:!0}}};a.Ord=g;a.abs=function(a){return function(b){return function(c){var d=h(a)(c)(e.zero(b["__superclass_Data.Semiring.Semiring_0"]()));
if(d)return c;if(!d)return f.negate(b)(c);throw Error("Failed pattern match at Data.Ord line 158, column 9 - line 158, column 42: "+[d.constructor.name]);}}};a.compare=function(a){return a.compare};a.greaterThanOrEq=h;a.max=function(a){return function(b){return function(c){var e=(0,a.compare)(b)(c);if(e instanceof d.LT)return c;if(e instanceof d.EQ||e instanceof d.GT)return b;throw Error("Failed pattern match at Data.Ord line 122, column 3 - line 125, column 12: "+[e.constructor.name]);}}};a.min=
function(a){return function(b){return function(c){var e=(0,a.compare)(b)(c);if(e instanceof d.LT||e instanceof d.EQ)return b;if(e instanceof d.GT)return c;throw Error("Failed pattern match at Data.Ord line 113, column 3 - line 116, column 12: "+[e.constructor.name]);}}};a.ordInt=c;a.ordNumber=k})(PS["Data.Ord"]=PS["Data.Ord"]||{});
(function(a){var b=PS["Data.Bounded"],c=PS["Data.Ord"],d=function(a,b,c){this["__superclass_Data.Ord.Ord_0"]=a;this.bottom=b;this.top=c},b=new d(function(){return c.ordInt},b.bottomInt,b.topInt);a.Bounded=d;a.bottom=function(a){return a.bottom};a.top=function(a){return a.top};a.boundedInt=b})(PS["Data.Bounded"]=PS["Data.Bounded"]||{});
(function(a){a.foldrArray=function(a){return function(c){return function(d){for(var f=c,e=d.length-1;0<=e;e--)f=a(d[e])(f);return f}}};a.foldlArray=function(a){return function(c){return function(d){for(var f=c,e=d.length,g=0;g<e;g++)f=a(f)(d[g]);return f}}}})(PS["Data.Foldable"]=PS["Data.Foldable"]||{});
(function(a){var b=PS["Control.Applicative"],c=PS["Control.Plus"],d=PS["Data.Unit"];a.MonadZero=function(a,b){this["__superclass_Control.Alternative.Alternative_1"]=a;this["__superclass_Control.Monad.Monad_0"]=b};a.guard=function(a){return function(e){if(e)return b.pure(a["__superclass_Control.Alternative.Alternative_1"]()["__superclass_Control.Applicative.Applicative_0"]())(d.unit);if(!e)return c.empty(a["__superclass_Control.Alternative.Alternative_1"]()["__superclass_Control.Plus.Plus_1"]());throw Error("Failed pattern match at Control.MonadZero line 52, column 1 - line 52, column 23: "+
[e.constructor.name]);}}})(PS["Control.MonadZero"]=PS["Control.MonadZero"]||{});(function(a){a.Monoid=function(a,c){this["__superclass_Data.Semigroup.Semigroup_0"]=a;this.mempty=c};a.mempty=function(a){return a.mempty}})(PS["Data.Monoid"]=PS["Data.Monoid"]||{});
(function(a){var b=PS["Control.Alt"],c=PS["Control.Alternative"],d=PS["Control.Applicative"],f=PS["Control.Apply"],e=PS["Control.Bind"],g=PS["Control.Monad"],k=PS["Control.MonadZero"],h=PS["Control.Plus"],l=PS["Data.Eq"],n=PS["Data.Function"],q=PS["Data.Functor"],m=PS["Control.Category"],r=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),p=function(){function a(){}a.value=new a;return a}(),u=function(a){return function(b){return function(c){if(c instanceof p)return a;
if(c instanceof r)return b(c.value0);throw Error("Failed pattern match at Data.Maybe line 232, column 1 - line 232, column 22: "+[a.constructor.name,b.constructor.name,c.constructor.name]);}}},n=u(!1)(n["const"](!0)),w=new q.Functor(function(a){return function(b){return b instanceof r?new r(a(b.value0)):p.value}}),v=new f.Apply(function(){return w},function(a){return function(b){if(a instanceof r)return q.map(w)(a.value0)(b);if(a instanceof p)return p.value;throw Error("Failed pattern match at Data.Maybe line 78, column 3 - line 78, column 31: "+
[a.constructor.name,b.constructor.name]);}}),z=new e.Bind(function(){return v},function(a){return function(b){if(a instanceof r)return b(a.value0);if(a instanceof p)return p.value;throw Error("Failed pattern match at Data.Maybe line 137, column 3 - line 137, column 24: "+[a.constructor.name,b.constructor.name]);}}),A=new d.Applicative(function(){return v},r.create),t=new g.Monad(function(){return A},function(){return z}),x=new b.Alt(function(){return w},function(a){return function(b){return a instanceof
p?b:a}}),y=new h.Plus(function(){return x},p.value),B=new c.Alternative(function(){return A},function(){return y}),b=new k.MonadZero(function(){return B},function(){return t});a.Just=r;a.Nothing=p;a.fromJust=function(a){return function(b){var c=function(a){return function(a){return a}}(a);if(b instanceof r)b=b.value0;else throw Error("Failed pattern match at Data.Maybe line 283, column 1 - line 283, column 21: "+[b.constructor.name]);return c(b)}};a.fromMaybe=function(a){return u(a)(m.id(m.categoryFn))};
a.isJust=n;a.maybe=u;a.functorMaybe=w;a.applyMaybe=v;a.applicativeMaybe=A;a.altMaybe=x;a.plusMaybe=y;a.alternativeMaybe=B;a.bindMaybe=z;a.monadMaybe=t;a.monadZeroMaybe=b;a.eqMaybe=function(a){return new l.Eq(function(b){return function(c){return b instanceof p&&c instanceof p?!0:b instanceof r&&c instanceof r?l.eq(a)(b.value0)(c.value0):!1}})}})(PS["Data.Maybe"]=PS["Data.Maybe"]||{});
(function(a){var b=PS["Data.Maybe"],c=PS["Data.Monoid"],d=new PS["Data.Semigroup"].Semigroup(function(a){return function(c){return a instanceof b.Just?a:c}}),c=new c.Monoid(function(){return d},b.Nothing.value);a.First=function(a){return a};a.runFirst=function(a){return a};a.semigroupFirst=d;a.monoidFirst=c})(PS["Data.Maybe.First"]=PS["Data.Maybe.First"]||{});
(function(a){a.boolConj=function(a){return function(c){return a&&c}};a.boolDisj=function(a){return function(c){return a||c}};a.boolNot=function(a){return!a}})(PS["Data.HeytingAlgebra"]=PS["Data.HeytingAlgebra"]||{});
(function(a){var b=PS["Data.HeytingAlgebra"],c=function(a,b,c,d,h,l){this.conj=a;this.disj=b;this.ff=c;this.implies=d;this.not=h;this.tt=l},d=new c(b.boolConj,b.boolDisj,!1,function(a){return function(b){return(0,d.disj)((0,d.not)(a))(b)}},b.boolNot,!0);a.HeytingAlgebra=c;a.conj=function(a){return a.conj};a.disj=function(a){return a.disj};a.ff=function(a){return a.ff};a.implies=function(a){return a.implies};a.not=function(a){return a.not};a.tt=function(a){return a.tt};a.heytingAlgebraBoolean=d})(PS["Data.HeytingAlgebra"]=
PS["Data.HeytingAlgebra"]||{});(function(a){var b=PS["Data.Functor"];a.Newtype=function(a,b){this.unwrap=a;this.wrap=b};a.alaF=function(a){return function(d){return function(f){return function(e){return function(g){return function(g){return function(h){return b.map(d)(e.unwrap)(g(b.map(a)(f.wrap)(h)))}}}}}}};a.unwrap=function(a){return a.unwrap};a.wrap=function(a){return a.wrap}})(PS["Data.Newtype"]=PS["Data.Newtype"]||{});
(function(a){var b=PS["Data.HeytingAlgebra"],c=PS["Data.Monoid"],d=PS["Data.Semigroup"],f=function(a){return a},e=function(a){return new d.Semigroup(function(c){return function(d){return b.conj(a)(c)(d)}})},g=new PS["Data.Newtype"].Newtype(function(a){return a},f);a.Conj=f;a.newtypeConj=g;a.semigroupConj=e;a.monoidConj=function(a){return new c.Monoid(function(){return e(a)},b.tt(a))}})(PS["Data.Monoid.Conj"]=PS["Data.Monoid.Conj"]||{});
(function(a){var b=PS["Data.Foldable"],c=PS["Data.Monoid"],d=PS["Data.Monoid.Conj"],f=PS["Data.Newtype"],e=PS["Control.Apply"],g=PS["Control.Applicative"],k=PS["Data.Unit"],h=PS["Data.Function"],l=PS["Data.Semigroup"],n=PS["Data.Semiring"],q=PS["Data.Functor"],m=function(a,b,c){this.foldMap=a;this.foldl=b;this.foldr=c},r=function(a){return function(b){return function(c){return(0,b.foldr)(function(b){return e.applySecond(a["__superclass_Control.Apply.Apply_0"]())(c(b))})(g.pure(a)(k.unit))}}},p=function(a){return function(b){return function(d){return function(e){return(0,a.foldr)(function(a){return function(c){return l.append(b["__superclass_Data.Semigroup.Semigroup_0"]())(d(a))(c)}})(c.mempty(b))(e)}}}},
u=new m(function(a){return p(u)(a)},b.foldlArray,b.foldrArray);a.Foldable=m;a.all=function(a){return function(b){return function(c){return f.alaF(q.functorFn)(q.functorFn)(d.newtypeConj)(d.newtypeConj)(d.Conj)((0,a.foldMap)(d.monoidConj(b)))(c)}}};a.foldMap=function(a){return a.foldMap};a.foldMapDefaultR=p;a.foldl=function(a){return a.foldl};a.foldr=function(a){return a.foldr};a.for_=function(a){return function(b){return h.flip(r(a)(b))}};a.sum=function(a){return function(b){return(0,a.foldl)(n.add(b))(n.zero(b))}};
a.traverse_=r;a.foldableArray=u})(PS["Data.Foldable"]=PS["Data.Foldable"]||{});
(function(a){a.traverseArrayImpl=function(){function a(b){this.fn=b}function c(a){return function(b){return new e(a,b)}}function d(a){for(var b=[];a!==f;)b.push(a.head),a=a.tail;return b}var f={},e=function(a,b){this.head=a;this.tail=b};return function(e){return function(k){return function(h){return function(l){var n=function(d,f,h){if(0===f)return d;var p=h[f-1];return new a(function(){var a=n,b;b=e(k(c)(l(p)))(d);return a(b,f-1,h)})};return function(c){for(c=n(h(f),c.length,c);c instanceof a;)c=
c.fn();return k(d)(c)}}}}}}()})(PS["Data.Traversable"]=PS["Data.Traversable"]||{});
(function(a){var b=PS["Data.Traversable"],c=PS["Data.Foldable"],d=PS["Control.Apply"],f=PS["Data.Functor"],e=PS["Control.Applicative"],g=PS["Control.Category"],k=function(a,b,c,d){this["__superclass_Data.Foldable.Foldable_1"]=a;this["__superclass_Data.Functor.Functor_0"]=b;this.sequence=c;this.traverse=d},h=function(a){return function(b){return function(c){return(0,a.traverse)(b)(g.id(g.categoryFn))(c)}}},l=new k(function(){return c.foldableArray},function(){return f.functorArray},function(a){return h(l)(a)},
function(a){return b.traverseArrayImpl(d.apply(a["__superclass_Control.Apply.Apply_0"]()))(f.map(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]()))(e.pure(a))});a.Traversable=k;a["for"]=function(a){return function(b){return function(c){return function(d){return(0,b.traverse)(a)(d)(c)}}}};a.sequence=function(a){return a.sequence};a.sequenceDefault=h;a.traverse=function(a){return a.traverse};a.traverseDefault=function(a){return function(b){return function(c){return function(d){return(0,a.sequence)(b)(f.map(a["__superclass_Data.Functor.Functor_0"]())(c)(d))}}}};
a.traversableArray=l})(PS["Data.Traversable"]=PS["Data.Traversable"]||{});
(function(a){var b=PS["Control.Applicative"],c=PS["Control.Apply"],d=PS["Control.Bind"],f=PS["Data.Bifunctor"],e=PS["Data.Functor"],g=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),k=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),h=new e.Functor(function(a){return function(b){if(b instanceof g)return new g(b.value0);if(b instanceof k)return new k(a(b.value0));throw Error("Failed pattern match at Data.Either line 46, column 3 - line 46, column 26: "+
[a.constructor.name,b.constructor.name]);}}),l=function(a){return function(b){return function(c){if(c instanceof g)return a(c.value0);if(c instanceof k)return b(c.value0);throw Error("Failed pattern match at Data.Either line 243, column 1 - line 243, column 26: "+[a.constructor.name,b.constructor.name,c.constructor.name]);}}},f=new f.Bifunctor(function(a){return function(b){return function(c){if(c instanceof g)return new g(a(c.value0));if(c instanceof k)return new k(b(c.value0));throw Error("Failed pattern match at Data.Either line 53, column 3 - line 53, column 34: "+
[a.constructor.name,b.constructor.name,c.constructor.name]);}}}),n=new c.Apply(function(){return h},function(a){return function(b){if(a instanceof g)return new g(a.value0);if(a instanceof k)return e.map(h)(a.value0)(b);throw Error("Failed pattern match at Data.Either line 89, column 3 - line 89, column 28: "+[a.constructor.name,b.constructor.name]);}}),c=new d.Bind(function(){return n},l(function(a){return function(b){return new g(a)}})(function(a){return function(b){return b(a)}})),b=new b.Applicative(function(){return n},
k.create);a.Left=g;a.Right=k;a.either=l;a.functorEither=h;a.bifunctorEither=f;a.applyEither=n;a.applicativeEither=b;a.bindEither=c})(PS["Data.Either"]=PS["Data.Either"]||{});
(function(a){a.fromNumberImpl=function(a){return function(c){return function(d){return(d|0)===d?a(d):c}}};a.toNumber=function(a){return a};a.fromStringAsImpl=function(a){return function(c){return function(d){var f;f=11>d?"[0-"+(d-1).toString()+"]":11===d?"[0-9a]":"[0-9a-"+String.fromCharCode(86+d)+"]";var e=new RegExp("^[\\+\\-]?"+f+"+$","i");return function(f){return e.test(f)?(f=parseInt(f,d),(f|0)===f?a(f):c):c}}}}})(PS["Data.Int"]=PS["Data.Int"]||{});
(function(a){a.otherwise=!0})(PS["Data.Boolean"]=PS["Data.Boolean"]||{});(function(a){a.and=function(a){return function(c){return a&c}};a.or=function(a){return function(c){return a|c}}})(PS["Data.Int.Bits"]=PS["Data.Int.Bits"]||{});(function(a){var b=PS["Data.Int.Bits"];a.and=b.and;a.or=b.or})(PS["Data.Int.Bits"]=PS["Data.Int.Bits"]||{});(function(a){a.abs=Math.abs;a.ceil=Math.ceil;a.round=Math.round;a.sqrt=Math.sqrt;a.pi=Math.PI})(PS.Math=PS.Math||{});
(function(a){var b=PS.Math;a.abs=b.abs;a.ceil=b.ceil;a.pi=b.pi;a.round=b.round;a.sqrt=b.sqrt})(PS.Math=PS.Math||{});(function(a){a.unsafePartial=function(a){return a()}})(PS["Partial.Unsafe"]=PS["Partial.Unsafe"]||{});(function(a){a.crashWith=function(){return function(a){throw Error(a);}}})(PS.Partial=PS.Partial||{});(function(a){a.crashWith=PS.Partial.crashWith})(PS.Partial=PS.Partial||{});
(function(a){var b=PS["Partial.Unsafe"],c=PS.Partial;a.unsafeCrashWith=function(a){return b.unsafePartial(function(b){return c.crashWith(b)(a)})};a.unsafePartial=b.unsafePartial})(PS["Partial.Unsafe"]=PS["Partial.Unsafe"]||{});
(function(a){var b=PS["Data.Int"],c=PS["Data.Boolean"],d=PS["Data.Bounded"],f=PS["Data.Maybe"],e=PS.Math,g=PS["Partial.Unsafe"],k=b.fromStringAsImpl(f.Just.create)(f.Nothing.value),h=k(10),l=b.fromNumberImpl(f.Just.create)(f.Nothing.value),n=function(a){if(a>=b.toNumber(d.top(d.boundedInt)))return d.top(d.boundedInt);if(a<=b.toNumber(d.bottom(d.boundedInt)))return d.bottom(d.boundedInt);if(c.otherwise)return g.unsafePartial(function(b){return f.fromJust(b)(l(a))});throw Error("Failed pattern match at Data.Int line 65, column 1 - line 68, column 56: "+
[a.constructor.name]);};a.ceil=function(a){return n(e.ceil(a))};a.fromNumber=l;a.fromString=h;a.fromStringAs=k;a.round=function(a){return n(e.round(a))};a.toNumber=b.toNumber})(PS["Data.Int"]=PS["Data.Int"]||{});
(function(a){var b=PS["Data.Foreign"],c=PS["Data.Either"],d=PS["Data.Show"],f=PS["Control.Applicative"],e=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),g=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),k=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),h=function(){function a(b){this.value0=
b}a.create=function(b){return new a(b)};return a}(),l=function(a){return function(d){return b.tagOf(d)===a?f.pure(c.applicativeEither)(b.unsafeFromForeign(d)):new c.Left(new e(a,b.tagOf(d)))}},n=new d.Show(function(a){if(a instanceof e)return"Type mismatch: expected "+(a.value0+(", found "+a.value1));if(a instanceof g)return"Error at array index "+(d.show(d.showInt)(a.value0)+(": "+d.show(n)(a.value1)));if(a instanceof k)return"Error at property "+(d.show(d.showString)(a.value0)+(": "+d.show(n)(a.value1)));
if(a instanceof h)return"JSON error: "+a.value0;throw Error("Failed pattern match at Data.Foreign line 55, column 3 - line 55, column 87: "+[a.constructor.name]);}),q=l("String");a.TypeMismatch=e;a.ErrorAtIndex=g;a.ErrorAtProperty=k;a.JSONError=h;a.readString=q;a.unsafeReadTagged=l;a.showForeignError=n})(PS["Data.Foreign"]=PS["Data.Foreign"]||{});
(function(a){var b=PS["Control.Monad.Eff.JQuery"];a.getValue=b.getValue;a.on=b.on;a.preventDefault=b.preventDefault;a.select=b.select})(PS["Control.Monad.Eff.JQuery"]=PS["Control.Monad.Eff.JQuery"]||{});
(function(a){a.newRef=function(a){return function(){return{value:a}}};a.readRef=function(a){return function(){return a.value}};a["modifyRef'"]=function(a){return function(c){return function(){var d=c(a.value);a.value=d.state;return d.value}}}})(PS["Control.Monad.Eff.Ref"]=PS["Control.Monad.Eff.Ref"]||{});
(function(a){var b=PS["Control.Monad.Eff.Ref"],c=PS["Data.Unit"];a.modifyRef=function(a){return function(f){return b["modifyRef'"](a)(function(a){return{state:f(a),value:c.unit}})}};a["modifyRef'"]=b["modifyRef'"];a.newRef=b.newRef;a.readRef=b.readRef})(PS["Control.Monad.Eff.Ref"]=PS["Control.Monad.Eff.Ref"]||{});
(function(a){var b=PS["Data.Ring"],c=function(a){this["__superclass_Data.Ring.Ring_0"]=a},d=new c(function(){return b.ringNumber});a.CommutativeRing=c;a.commutativeRingNumber=d})(PS["Data.CommutativeRing"]=PS["Data.CommutativeRing"]||{});
(function(a){var b=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(f){return new a(b,f)}};return a}();a.Tuple=b;a.fst=function(a){return a.value0};a.snd=function(a){return a.value1}})(PS["Data.Tuple"]=PS["Data.Tuple"]||{});
(function(a){var b=PS["Data.Tuple"],c=PS["Control.Apply"],d=PS["Control.Applicative"],f=PS["Control.Bind"],e=PS["Data.Unit"],g=new PS["Data.Functor"].Functor(function(a){return function(c){return function(d){var e=c(d);d=b.snd(e);e=b.fst(e);return new b.Tuple(a(e),d)}}}),k=new c.Apply(function(){return g},function(a){return function(c){return function(d){var e=a(d);d=b.snd(e);var f=c(d);d=b.snd(f);e=b.fst(e);f=b.fst(f);return new b.Tuple(e(f),d)}}}),c=new f.Bind(function(){return k},function(a){return function(c){return function(d){var e=
a(d);d=b.snd(e);e=b.fst(e);e=c(e)(d);d=b.fst(e);e=b.snd(e);return new b.Tuple(d,e)}}}),d=new d.Applicative(function(){return k},function(a){return b.Tuple.create(a)});a.evalState=function(a){return function(c){return b.fst(a(c))}};a.execState=function(a){return function(c){return b.snd(a(c))}};a.get=function(a){return new b.Tuple(a,a)};a.modify=function(a){return function(c){return new b.Tuple(e.unit,a(c))}};a.put=function(a){return function(c){return new b.Tuple(e.unit,a)}};a.runState=function(a){return a};
a.functorState=g;a.applyState=k;a.applicativeState=d;a.bindState=c})(PS["Control.Monad.Transformerless.State"]=PS["Control.Monad.Transformerless.State"]||{});(function(a){a.window=function(){return window}})(PS["DOM.HTML"]=PS["DOM.HTML"]||{});(function(a){a.window=PS["DOM.HTML"].window})(PS["DOM.HTML"]=PS["DOM.HTML"]||{});
(function(a){a.innerWidth=function(a){return function(){return a.innerWidth}};a.innerHeight=function(a){return function(){return a.innerHeight}}})(PS["DOM.HTML.Window"]=PS["DOM.HTML.Window"]||{});(function(a){var b=PS["DOM.HTML.Window"];a.innerHeight=b.innerHeight;a.innerWidth=b.innerWidth})(PS["DOM.HTML.Window"]=PS["DOM.HTML.Window"]||{});
(function(a){a.range=function(a){return function(c){for(var d=a>c?-1:1,f=[],e=a,g=0;e!==c;e+=d)f[g++]=e;f[g]=e;return f}};a.fromFoldableImpl=function(){function a(b,c){this.head=b;this.tail=c}function c(c){return function(d){return new a(c,d)}}var d={};return function(a){return function(b){b=a(c)(d)(b);for(var g=[],k=0;b!==d;)g[k++]=b.head,b=b.tail;return g}}}();a.length=function(a){return a.length};a.cons=function(a){return function(c){return[a].concat(c)}};a.snoc=function(a){return function(c){var d=
a.slice();d.push(c);return d}};a["uncons'"]=function(a){return function(c){return function(d){return 0===d.length?a({}):c(d[0])(d.slice(1))}}};a.findIndexImpl=function(a){return function(c){return function(d){return function(f){for(var e=0,g=f.length;e<g;e++)if(d(f[e]))return a(e);return c}}}};a._insertAt=function(a){return function(c){return function(d){return function(f){return function(e){if(0>d||d>e.length)return c;e=e.slice();e.splice(d,0,f);return a(e)}}}}};a._deleteAt=function(a){return function(c){return function(d){return function(f){if(0>
d||d>=f.length)return c;f=f.slice();f.splice(d,1);return a(f)}}}};a._updateAt=function(a){return function(c){return function(d){return function(f){return function(e){if(0>d||d>=e.length)return c;e=e.slice();e[d]=f;return a(e)}}}}};a.concat=function(a){for(var c=[],d=0,f=a.length;d<f;d++)for(var e=a[d],g=0,k=e.length;g<k;g++)c.push(e[g]);return c};a.filter=function(a){return function(c){return c.filter(a)}};a.slice=function(a){return function(c){return function(d){return d.slice(a,c)}}};a.take=function(a){return function(c){return 1>
a?[]:c.slice(0,a)}};a.drop=function(a){return function(c){return 1>a?c:c.slice(a)}};a.zipWith=function(a){return function(c){return function(d){for(var f=c.length<d.length?c.length:d.length,e=Array(f),g=0;g<f;g++)e[g]=a(c[g])(d[g]);return e}}}})(PS["Data.Array"]=PS["Data.Array"]||{});
(function(a){var b=PS["Data.Array"],c=PS["Data.Foldable"],d=PS["Data.Maybe"],f=PS["Partial.Unsafe"],e=PS["Data.Function"],g=PS["Data.Eq"],k=PS["Data.Boolean"],h=PS["Control.Bind"],l=b._updateAt(d.Just.create)(d.Nothing.value),n=b["uncons'"](e["const"](d.Nothing.value))(function(a){return function(b){return new d.Just({head:a,tail:b})}}),q=b["uncons'"](e["const"](d.Nothing.value))(function(a){return function(a){return new d.Just(a)}}),m=function(a){return function(c){var e=n(c);if(e instanceof d.Just)return b.cons(e.value0.head)(m(a)(b.filter(function(b){return!a(e.value0.head)(b)})(e.value0.tail)));
if(e instanceof d.Nothing)return[];throw Error("Failed pattern match at Data.Array line 525, column 3 - line 527, column 18: "+[e.constructor.name]);}},r=b._insertAt(d.Just.create)(d.Nothing.value),p=b["uncons'"](e["const"](d.Nothing.value))(function(a){return function(b){return new d.Just(a)}}),u=b.findIndexImpl(d.Just.create)(d.Nothing.value),w=function(a){return function(c){return function(e){return b.filter(function(b){return d.isJust(u(a(b))(e))})(c)}}},v=b._deleteAt(d.Just.create)(d.Nothing.value),
z=function(a){return function(b){return function(c){return 0===c.length?[]:d.maybe(c)(function(a){return f.unsafePartial(function(b){return d.fromJust(b)(v(a)(c))})})(u(a(b))(c))}}},A=function(a){return function(c){return function(d){if(0===b.length(c))return[];if(k.otherwise)return b["uncons'"](e["const"](c))(function(b){return function(d){return A(a)(z(g.eq(a))(b)(c))(d)}})(d);throw Error("Failed pattern match at Data.Array line 557, column 1 - line 559, column 67: "+[c.constructor.name,d.constructor.name]);
}}},h=e.flip(h.bind(h.bindArray));a.concatMap=h;a.deleteAt=v;a.deleteBy=z;a.difference=A;a.findIndex=u;a.fromFoldable=function(a){return b.fromFoldableImpl(c.foldr(a))};a.head=p;a.insertAt=r;a.intersect=function(a){return w(g.eq(a))};a.intersectBy=w;a.nub=function(a){return m(g.eq(a))};a.nubBy=m;a.tail=q;a.uncons=n;a.updateAt=l;a.drop=b.drop;a.length=b.length;a.range=b.range;a.snoc=b.snoc;a.take=b.take;a.zipWith=b.zipWith})(PS["Data.Array"]=PS["Data.Array"]||{});
(function(a){a.unsafeIndexImpl=function(a){return function(c){return a[c]}}})(PS["Data.Array.Partial"]=PS["Data.Array.Partial"]||{});(function(a){var b=PS["Data.Array.Partial"];a.unsafeIndex=function(a){return b.unsafeIndexImpl}})(PS["Data.Array.Partial"]=PS["Data.Array.Partial"]||{});
(function(a){var b=PS["Data.Ring"],c=PS["Data.Eq"],d=PS["Data.Ord"],f=PS.Math,e=PS["Data.Ordering"],g=function(a,b){this["__superclass_Data.Ord.Ord_0"]=a;this.nearZero=b},k=new g(function(){return d.ordNumber},function(a){return 1E-12>=f.abs(a)}),h=new g(function(){return d.ordInt},function(a){return 0===a}),l=function(a){return function(c){return function(f){return function(g){var h=(0,c.nearZero)(b.sub(a)(f)(g));if(h)return e.EQ.value;if(!h)return d.compare(c["__superclass_Data.Ord.Ord_0"]())(f)(g);
throw Error("Failed pattern match at Linear.Epsilon line 19, column 21 - line 21, column 40: "+[h.constructor.name]);}}}},n=function(a){return function(b){return function(d){return function(f){return c.eq(e.eqOrdering)(l(a)(b)(d)(f))(e.EQ.value)}}}};a.Approx=function(a){return a};a.Epsilon=g;a.approxCompare=l;a.approxEQ=n;a.approxGT=function(a){return function(b){return function(d){return function(f){return c.eq(e.eqOrdering)(l(a)(b)(d)(f))(e.GT.value)}}}};a.approxGreaterThanOrEq=function(a){return function(b){return function(d){return function(f){f=
l(a)(b)(d)(f);return c.eq(e.eqOrdering)(f)(e.GT.value)||c.eq(e.eqOrdering)(f)(e.EQ.value)}}}};a.approxLT=function(a){return function(b){return function(d){return function(f){return c.eq(e.eqOrdering)(l(a)(b)(d)(f))(e.LT.value)}}}};a.approxLessThanOrEq=function(a){return function(b){return function(d){return function(f){f=l(a)(b)(d)(f);return c.eq(e.eqOrdering)(f)(e.LT.value)||c.eq(e.eqOrdering)(f)(e.EQ.value)}}}};a.nearZero=function(a){return a.nearZero};a.toExact=function(a){return a};a.numberEpsilon=
k;a.intEpsilon=h;a.approxEqInstance=function(a){return function(b){return new c.Eq(function(c){return function(d){return n(a)(b)(c)(d)}})}}})(PS["Linear.Epsilon"]=PS["Linear.Epsilon"]||{});(function(a){a.numDiv=function(a){return function(c){return a/c}}})(PS["Data.EuclideanRing"]=PS["Data.EuclideanRing"]||{});
(function(a){var b=PS["Data.CommutativeRing"],c=function(a,b,c,d){this["__superclass_Data.CommutativeRing.CommutativeRing_0"]=a;this.degree=b;this.div=c;this.mod=d},d=new c(function(){return b.commutativeRingNumber},function(a){return 1},PS["Data.EuclideanRing"].numDiv,function(a){return function(a){return 0}});a.EuclideanRing=c;a.degree=function(a){return a.degree};a.div=function(a){return a.div};a.mod=function(a){return a.mod};a.euclideanRingNumber=d})(PS["Data.EuclideanRing"]=PS["Data.EuclideanRing"]||
{});
(function(a){var b=PS["Data.Functor"],c=PS["Data.Ring"],d=PS["Data.Semiring"],f=PS["Data.EuclideanRing"],e=PS["Data.Function"],g=PS["Control.Applicative"],k=PS["Control.Apply"],h=function(a){return function(c){return function(e){return function(f){return b.map(a)(d.mul(c)(e))(f)}}}},l=function(a){return function(c){return function(d){return function(e){return k.apply(a["__superclass_Control.Apply.Apply_0"]())(b.map(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(c)(d))(e)}}}},n=
function(a){return function(b){return function(c){return function(e){return l(a)(d.add(b))(c)(e)}}}};a.Additive=function(a,b,c,d,e,f,g){this["__superclass_Data.Functor.Functor_0"]=a;this.aZero=b;this.lerp=c;this.liftI2=d;this.liftU2=e;this.vAddV=f;this.vSubV=g};a.aZero=function(a){return a.aZero};a.defaultLerp=function(a){return function(b){return function(e){return function(f){return function(g){return n(a)(b["__superclass_Data.Semiring.Semiring_0"]())(h(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(b["__superclass_Data.Semiring.Semiring_0"]())(e)(f))(h(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(b["__superclass_Data.Semiring.Semiring_0"]())(c.sub(b)(d.one(b["__superclass_Data.Semiring.Semiring_0"]()))(e))(g))}}}}};
a.defaultLiftI2=l;a.defaultLiftU2=function(a){return l(a)};a.defaultVAddV=n;a.defaultVSubV=function(a){return function(b){return function(d){return function(e){return l(a)(c.sub(b))(d)(e)}}}};a.defaultZero=function(a){return function(b){return g.pure(a)(d.zero(b))}};a.fDivS=function(a){return function(c){return function(d){return function(g){return b.map(a)(e.flip(f.div(c))(g))(d)}}}};a.fMulS=function(a){return function(c){return function(f){return function(g){return b.map(a)(e.flip(d.mul(c))(g))(f)}}}};
a.lerp=function(a){return a.lerp};a.liftI2=function(a){return a.liftI2};a.liftU2=function(a){return a.liftU2};a.sMulF=h;a.vAddV=function(a){return a.vAddV};a.vSubV=function(a){return a.vSubV}})(PS["Linear.Vector"]=PS["Linear.Vector"]||{});
(function(a){var b=PS.Math,c=PS["Data.Foldable"],d=PS["Linear.Vector"],f=PS["Data.Semiring"],e=PS["Data.Ring"],g=PS["Data.EuclideanRing"],k=function(a){return function(b){return function(e){return function(g){return function(h){return c.sum(b)(e)(d.liftI2(a)(f.mul(e))(g)(h))}}}}},h=function(a){return function(b){return function(c){return function(d){return k(a)(b)(c)(d)(d)}}}},l=function(a){return function(c){return function(d){return b.sqrt(h(a)(c)(f.semiringNumber)(d))}}};a.Metric=function(a,b,
c,d,e,f,g){this["__superclass_Linear.Vector.Additive_0"]=a;this.distance=b;this.dot=c;this.norm=d;this.qd=e;this.quadrance=f;this.signorm=g};a.defaultDistance=function(a){return function(b){return function(c){return function(f){return l(a)(b)(d.vSubV(a)(e.ringNumber)(c)(f))}}}};a.defaultDot=k;a.defaultNorm=l;a.defaultQd=function(a){return function(b){return function(c){return function(e){return function(f){return h(a)(b)(c["__superclass_Data.Semiring.Semiring_0"]())(d.vSubV(a)(c)(e)(f))}}}}};a.defaultQuadrance=
h;a.defaultSignorm=function(a){return function(b){return function(c){return d.fDivS(a["__superclass_Data.Functor.Functor_0"]())(g.euclideanRingNumber)(c)(l(a)(b)(c))}}};a.distance=function(a){return a.distance};a.dot=function(a){return a.dot};a.norm=function(a){return a.norm};a.qd=function(a){return a.qd};a.quadrance=function(a){return a.quadrance};a.signorm=function(a){return a.signorm}})(PS["Linear.Metric"]=PS["Linear.Metric"]||{});
(function(a){var b=PS["Data.Foldable"],c=PS["Linear.Epsilon"],d=PS["Linear.Vector"],f=PS["Linear.Metric"],e=PS["Data.Semiring"],g=PS["Data.Ring"],k=PS["Data.Eq"],h=PS["Data.Ord"],l=PS["Data.Ordering"],n=PS["Data.Functor"],q=PS["Control.Apply"],m=PS["Control.Applicative"],r=PS["Data.Semigroup"],p=function(a){this.r2=a},u=new p(function(a){return a}),w=function(a){return new e.Semiring(function(b){return function(c){return{x:e.add(a)(b.x)(c.x),y:e.add(a)(b.y)(c.y)}}},function(b){return function(c){return{x:e.mul(a)(b.x)(c.x),
y:e.mul(a)(b.y)(c.y)}}},{x:e.one(a),y:e.one(a)},{x:e.zero(a),y:e.zero(a)})},v=new n.Functor(function(a){return function(b){return{x:a(b.x),y:a(b.y)}}}),z=new p(function(a){return a}),A=function(a){return new e.Semiring(function(b){return function(c){return{x:e.add(a)(b.x)(c.x),y:e.add(a)(b.y)(c.y)}}},function(b){return function(c){return{x:e.mul(a)(b.x)(c.x),y:e.mul(a)(b.y)(c.y)}}},{x:e.one(a),y:e.one(a)},{x:e.zero(a),y:e.zero(a)})},t=new n.Functor(function(a){return function(b){return{x:a(b.x),y:a(b.y)}}}),
x=new b.Foldable(function(a){return function(b){return function(c){return r.append(a["__superclass_Data.Semigroup.Semigroup_0"]())(b(c.x))(b(c.y))}}},function(a){return function(b){return function(c){return a(a(b)(c.x))(c.y)}}},function(a){return function(b){return function(c){return a(c.x)(a(c.y)(b))}}}),y=function(a){return new k.Eq(function(b){return function(c){return k.eq(a)(b.x)(c.x)&&k.eq(a)(b.y)(c.y)}})},B=function(a){return new h.Ord(function(){return y(a["__superclass_Data.Eq.Eq_0"]())},
function(b){return function(c){var d=h.compare(a)(b.x)(c.x);return d instanceof l.EQ?h.compare(a)(b.y)(c.y):d}})},E=function(a){return function(b){return{x:a,y:b}}},F=new q.Apply(function(){return t},function(a){return function(b){return E(a.x(b.x))(a.y(b.y))}}),D=new m.Applicative(function(){return F},function(a){return E(a)(a)}),C=new d.Additive(function(){return t},function(a){return d.defaultZero(D)(a)},function(a){return d.defaultLerp(D)(a)},d.defaultLiftI2(D),d.defaultLiftU2(D),function(a){return d.defaultVAddV(D)(a)},
function(a){return d.defaultVSubV(D)(a)}),b=new f.Metric(function(){return C},f.defaultDistance(C)(x),function(a){return f.defaultDot(C)(x)(a)},f.defaultNorm(C)(x),function(a){return f.defaultQd(C)(x)(a)},function(a){return f.defaultQuadrance(C)(x)(a)},f.defaultSignorm(C)(x));a.R2=p;a.crossZ=function(a){return function(b){return function(c){return g.sub(a)(e.mul(a["__superclass_Data.Semiring.Semiring_0"]())(b.x)(c.y))(e.mul(a["__superclass_Data.Semiring.Semiring_0"]())(b.y)(c.x))}}};a.invY=function(a){return function(b){return{x:b.x,
y:g.negate(a)(b.y)}}};a.p2=E;a.p2Diff=function(a){return function(b){return function(c){return{x:g.sub(a)(b.x)(c.x),y:g.sub(a)(b.y)(c.y)}}}};a.pAddV=function(a){return function(b){return function(c){return{x:e.add(a)(b.x)(c.x),y:e.add(a)(b.y)(c.y)}}}};a.r2=function(a){return a.r2};a.v2=function(a){return function(b){return{x:a,y:b}}};a.v2r2=u;a.p2r2=z;a.v2Semiring=w;a.p2Semiring=A;a.v2Ring=function(a){return new g.Ring(function(){return w(a["__superclass_Data.Semiring.Semiring_0"]())},function(b){return function(c){return{x:g.sub(a)(b.x)(c.x),
y:g.sub(a)(b.y)(c.y)}}})};a.p2Ring=function(a){return new g.Ring(function(){return A(a["__superclass_Data.Semiring.Semiring_0"]())},function(b){return function(c){return{x:g.sub(a)(b.x)(c.x),y:g.sub(a)(b.y)(c.y)}}})};a.p2Eq=y;a.p2Ord=B;a.v2Functor=v;a.p2Functor=t;a.p2Apply=F;a.p2Applicative=D;a.p2Additive=C;a.p2Metric=b;a.p2Epsilon=function(a){return new c.Epsilon(function(){return B(a["__superclass_Data.Ord.Ord_0"]())},function(b){return c.nearZero(a)(b.x)&&c.nearZero(a)(b.y)})};a.p2Foldable=x})(PS["Linear.R2"]=
PS["Linear.R2"]||{});
(function(a){var b=PS["Data.Foldable"],c=PS["Data.Maybe"],d=PS["Data.Monoid"],f=PS["Data.Semigroup"],e=function(){function a(){}a.value=new a;return a}(),g=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),k=new b.Foldable(function(a){return function(c){return b.foldl(k)(function(b){return function(d){return f.append(a["__superclass_Data.Semigroup.Semigroup_0"]())(b)(c(d))}})(d.mempty(a))}},function(){return function(a){return function(b){return function(c){var d=a,
f=b,k=c;a:for(;;){if(k instanceof e)return f;if(k instanceof g){c=d;f=d(f)(k.value0);k=k.value1;d=c;continue a}throw Error("Failed pattern match at Data.List line 734, column 3 - line 737, column 49: "+[d.constructor.name,f.constructor.name,k.constructor.name]);}}}}}(),function(a){return function(c){return function(d){if(d instanceof e)return c;if(d instanceof g)return a(d.value0)(b.foldr(k)(a)(c)(d.value1));throw Error("Failed pattern match at Data.List line 732, column 3 - line 732, column 20: "+
[a.constructor.name,c.constructor.name,d.constructor.name]);}}});a.Nil=e;a.Cons=g;a.fromFoldable=function(a){return b.foldr(a)(g.create)(e.value)};a.tail=function(a){if(a instanceof e)return c.Nothing.value;if(a instanceof g)return new c.Just(a.value1);throw Error("Failed pattern match at Data.List line 232, column 1 - line 232, column 19: "+[a.constructor.name]);};a.foldableList=k})(PS["Data.List"]=PS["Data.List"]||{});
(function(a){var b=PS["Data.Maybe"],c=PS["Linear.R2"],d=PS["Linear.Epsilon"],f=PS["Linear.Vector"],e=PS["Linear.Metric"],g=PS["Data.Functor"],k=PS["Data.Semiring"],h=PS["Data.Ring"],l=PS["Data.Ord"],n=PS["Data.EuclideanRing"],q=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),m=function(a){return function(b){var g=e.qd(c.p2Metric)(h.ringNumber)(b.value0)(b.value1),m=l.max(l.ordNumber)(0)(l.min(l.ordNumber)(1)(e.dot(c.p2Metric)(k.semiringNumber)(h.sub(c.p2Ring(h.ringNumber))(a)(b.value0))(h.sub(c.p2Ring(h.ringNumber))(b.value1)(b.value0))/
g)),m=c.pAddV(k.semiringNumber)(b.value0)(f.sMulF(c.v2Functor)(k.semiringNumber)(m)(c.p2Diff(h.ringNumber)(b.value1)(b.value0)));if(g=d.nearZero(d.numberEpsilon)(g))return b.value0;if(!g)return m;throw Error("Failed pattern match at Data.Segment line 70, column 28 - line 70, column 61: "+[g.constructor.name]);}},g=new g.Functor(function(a){return function(b){return new q(a(b.value0),a(b.value1))}});a.Seg=q;a.distance=function(a){return function(b){return e.distance(c.p2Metric)(a)(m(a)(b))}};a.inside=
function(a){return function(b){return function(e){return function(f){return d.approxLT(a)(b)(c.crossZ(a)(c.p2Diff(a)(f.value1)(f.value0))(c.p2Diff(a)(e)(f.value1)))(k.zero(a["__superclass_Data.Semiring.Semiring_0"]()))}}}};a.intersection=function(a){return function(e){return function(f){return function(g){var l=h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(f.value0.x)(f.value1.x))(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(g.value0.y)(g.value1.y)))(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(f.value0.y)(f.value1.y))(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(g.value0.x)(g.value1.x))),
m=d.nearZero(a)(l);if(m)return b.Nothing.value;if(!m){var q=h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(g.value0.x)(g.value1.y))(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(g.value0.y)(g.value1.x)),t=
h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(f.value0.x)(f.value1.y))(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(f.value0.y)(f.value1.x)),m=n.div(e)(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(t)(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(g.value0.x)(g.value1.x)))(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(f.value0.x)(f.value1.x))(q)))(l);
g=n.div(e)(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(t)(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(g.value0.y)(g.value1.y)))(k.mul(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]()["__superclass_Data.Semiring.Semiring_0"]())(h.sub(e["__superclass_Data.CommutativeRing.CommutativeRing_0"]()["__superclass_Data.Ring.Ring_0"]())(f.value0.y)(f.value1.y))(q)))(l);
return new b.Just(c.p2(m)(g))}throw Error("Failed pattern match at Data.Segment line 42, column 7 - line 48, column 32: "+[m.constructor.name]);}}}};a.nearestPoint=m;a.outside=function(a){return function(b){return function(e){return function(f){return d.approxGT(a)(b)(c.crossZ(a)(c.p2Diff(a)(f.value1)(f.value0))(c.p2Diff(a)(e)(f.value1)))(k.zero(a["__superclass_Data.Semiring.Semiring_0"]()))}}}};a.functorSeg=g})(PS["Data.Segment"]=PS["Data.Segment"]||{});
(function(a){var b=PS["Linear.R2"],c=PS["Linear.Epsilon"],d=PS["Data.Semiring"],f=function(){function a(b,c,d){this.value0=b;this.value1=c;this.value2=d}a.create=function(b){return function(c){return function(d){return new a(b,c,d)}}};return a}();a.Corner=f;a.clockWise=function(a){return function(f){return function(k){return c.approxLT(a)(f)(b.crossZ(a)(b.p2Diff(a)(k.value1)(k.value0))(b.p2Diff(a)(k.value2)(k.value1)))(d.zero(a["__superclass_Data.Semiring.Semiring_0"]()))}}};a.crossZ=function(a){return function(c){return function(c){return b.crossZ(a)(b.p2Diff(a)(c.value1)(c.value0))(b.p2Diff(a)(c.value2)(c.value1))}}};
a.isLine=function(a){return function(d){return function(f){return c.nearZero(d)(b.crossZ(a)(b.p2Diff(a)(f.value1)(f.value0))(b.p2Diff(a)(f.value2)(f.value1)))}}}})(PS["Data.Corner"]=PS["Data.Corner"]||{});
(function(a){var b=PS["Data.Traversable"],c=PS["Data.Foldable"],d=PS["Data.Maybe"],f=PS["Control.Monad.Transformerless.State"],e=PS["Partial.Unsafe"],g=PS["Data.Array"],k=PS["Data.Function"],h=PS["Control.Bind"],l=PS["Data.Boolean"],n=PS["Control.Applicative"],q=PS["Data.Unit"],m=PS["Control.Apply"],r=PS["Data.Functor"],p=function(a){return function(b){return function(c){return function(d){if(c(b))return h.bind(a["__superclass_Control.Bind.Bind_1"]())(d(b))(function(b){return p(a)(b)(c)(d)});if(l.otherwise)return n.pure(a["__superclass_Control.Applicative.Applicative_0"]())(q.unit);
throw Error("Failed pattern match at Utils line 30, column 1 - line 32, column 48: "+[b.constructor.name,c.constructor.name,d.constructor.name]);}}}};a.bug=e.unsafeCrashWith;a.enumerate=function(a){return function(c){return k.flip(f.evalState)(0)(b["for"](f.applicativeState)(a)(c)(function(a){return h.bind(f.bindState)(f.get)(function(b){return h.bind(f.bindState)(f.put(b+1|0))(function(){return n.pure(f.applicativeState)({idx:b,elem:a})})})}))}};a.foldlA2=function(a){return function(b){return function(e){return c.foldl(a)(function(a){return function(c){if(a instanceof
d.Nothing)return new d.Just(c);if(a instanceof d.Just)return new d.Just(m.apply(b["__superclass_Control.Apply.Apply_0"]())(r.map(b["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(e)(a.value0))(c));throw Error("Failed pattern match at Utils line 25, column 9 - line 25, column 30: "+[a.constructor.name,c.constructor.name]);}})(d.Nothing.value)}}};a.fromJust=function(a){return e.unsafePartial(function(b){return d.fromJust(b)(a)})};a.quot=function(a){return function(b){var c=
a%b,d=0>c;if(d)return c+b|0;if(!d)return c;throw Error("Failed pattern match at Utils line 48, column 15 - line 50, column 23: "+[d.constructor.name]);}};a.replicateA_=function(a){return function(b){return function(d){return c.traverse_(a)(c.foldableArray)(function(a){return d})(g.range(1)(b))}}};a.whileM_=p;a.zipWith3=function(a){return function(b){return function(c){return g.zipWith(k.apply)(g.zipWith(a)(b)(c))}}}})(PS.Utils=PS.Utils||{});
(function(a){var b=PS["Data.Maybe"],c=PS["Data.Array"],d=PS["Data.Array.Partial"],f=PS["Partial.Unsafe"],e=PS["Data.Foldable"],g=PS["Data.Traversable"],k=PS["Control.Monad.Transformerless.State"],h=PS["Data.List"],l=PS["Linear.Epsilon"],n=PS["Linear.R2"],q=PS["Data.Segment"],m=PS["Data.Corner"],r=PS.Utils,p=PS["Data.Functor"],u=PS["Data.Semigroup"],w=PS["Data.Semiring"],v=PS["Data.Function"],z=PS["Data.Ord"],A=PS["Data.Boolean"],t=PS["Data.Ring"],x=PS["Control.Bind"],y=PS["Control.Applicative"],B=
PS["Control.Category"],E=PS["Data.EuclideanRing"],F=PS["Data.HeytingAlgebra"],D=function(a){return a},C=function(a){return function(b){var d=r.quot(a)(c.length(b));return u.append(u.semigroupArray)(c.drop(d)(b))(c.take(d)(b))}},K=function(a){return function(b){return[a,n.p2(a.x)(b.y),b,n.p2(b.x)(a.y)]}},L=function(a){return function(b){return function(c){if(c instanceof h.Cons&&c.value1 instanceof h.Cons&&c.value1.value1 instanceof h.Cons){var d=m.isLine(a)(b)(new m.Corner(c.value0,c.value1.value0,
c.value1.value1.value0));if(d)return L(a)(b)(new h.Cons(c.value0,c.value1.value1));if(!d)return new h.Cons(c.value0,L(a)(b)(c.value1));throw Error("Failed pattern match at Data.Polygon line 180, column 3 - line 182, column 37: "+[d.constructor.name]);}return c}}},G=new p.Functor(function(a){return function(b){return p.map(p.functorArray)(a)(b)}}),M=new e.Foldable(function(a){return function(b){return function(c){return e.foldMap(e.foldableArray)(a)(b)(c)}}},function(a){return function(b){return function(c){return e.foldl(e.foldableArray)(a)(b)(c)}}},
function(a){return function(b){return function(c){return e.foldr(e.foldableArray)(a)(b)(c)}}}),H=new g.Traversable(function(){return M},function(){return G},function(a){return function(b){return p.map(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(D)(g.sequence(g.traversableArray)(a)(b))}},function(a){return function(b){return function(c){return p.map(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(D)(g.traverse(g.traversableArray)(a)(b)(c))}}}),
I=function(a){if(3>c.length(a))return b.Nothing.value;if(A.otherwise)return new b.Just(a);throw Error("Failed pattern match at Data.Polygon line 55, column 1 - line 56, column 39: "+[a.constructor.name]);},J=function(a){return function(d){return function(f){var g=function(a){return c.zipWith(q.Seg.create)(a)(C(1)(a))},h=v.flip(c.snoc);return I(function(a){return p.map(p.functorArray)(l.toExact)(c.nub(l.approxEqInstance(n.p2Ring(t.ringNumber))(n.p2Epsilon(l.numberEpsilon)))(p.map(p.functorArray)(l.Approx)(a)))}(v.flip(k.execState)(f)(e.for_(k.applicativeState)(e.foldableArray)(g(d))(function(c){var d=
new q.Seg(c.value0,c.value1);return x.bind(k.bindState)(k.get)(function(c){return x.bind(k.bindState)(k.put([]))(function(){return e.for_(k.applicativeState)(e.foldableArray)(g(c))(function(c){var e=new q.Seg(c.value0,c.value1),f=a(c.value1)(d);if(f)return x.bind(k.bindState)(y.unless(k.applicativeState)(a(c.value0)(d))(k.modify(b.maybe(B.id(B.categoryFn))(h)(q.intersection(l.numberEpsilon)(E.euclideanRingNumber)(e)(d)))))(function(){return k.modify(h(c.value1))});if(!f)return y.when(k.applicativeState)(a(c.value0)(d))(k.modify(b.maybe(B.id(B.categoryFn))(h)(q.intersection(l.numberEpsilon)(E.euclideanRingNumber)(e)(d))));
throw Error("Failed pattern match at Data.Polygon line 149, column 9 - line 156, column 70: "+[f.constructor.name]);})})})}))))}}},N=function(a){return function(b){return f.unsafePartial(function(e){return d.unsafeIndex(e)(a)(r.quot(b)(c.length(a)))})}},O=function(a){var d=x.bind(b.bindMaybe)(c.uncons(a))(function(d){var e=c.snoc(d.tail)(d.head);return x.bind(b.bindMaybe)(c.uncons(e))(function(d){d=c.snoc(d.tail)(d.head);return y.pure(b.applicativeMaybe)(r.zipWith3(m.Corner.create)(a)(e)(d))})});
if(d instanceof b.Nothing)return r.bug("corners: got bad polygon");if(d instanceof b.Just)return d.value0;throw Error("Failed pattern match at Data.Polygon line 72, column 22 - line 74, column 37: "+[d.constructor.name]);},P=function(a){return function(b){return function(c){return e.all(e.foldableArray)(F.heytingAlgebraBoolean)(m.clockWise(a)(b))(O(c))}}},Q=function(a){return I(c.fromFoldable(h.foldableList)(a))};a.clip=function(a){return function(b){var c;if(c=P(t.ringNumber)(l.numberEpsilon)(a))c=
q.inside(t.ringNumber)(l.numberEpsilon);else{if(c)throw Error("Failed pattern match at Data.Polygon line 165, column 16 - line 165, column 66: "+[c.constructor.name]);c=q.outside(t.ringNumber)(l.numberEpsilon)}return J(c)(a)(b)}};a.clockWise=P;a.corners=O;a.edges=function(a){var d=c.uncons(a);if(d instanceof b.Nothing)return r.bug("edges: got empty polygon");if(d instanceof b.Just)return c.zipWith(q.Seg.create)(a)(c.snoc(d.value0.tail)(d.value0.head));throw Error("Failed pattern match at Data.Polygon line 62, column 19 - line 65, column 60: "+
[d.constructor.name]);};a.index=N;a.insertAt=function(a){return function(b){return function(d){var e=r.quot(a)(c.length(d));return r.fromJust(c.insertAt(e)(b)(d))}}};a.isConvex=function(a){return function(b){return function(c){c=p.map(p.functorArray)(m.crossZ(a)(b))(O(c));return e.all(e.foldableArray)(F.heytingAlgebraBoolean)(function(c){return l.approxGreaterThanOrEq(a)(b)(c)(w.zero(a["__superclass_Data.Semiring.Semiring_0"]()))})(c)||e.all(e.foldableArray)(F.heytingAlgebraBoolean)(function(c){return l.approxLessThanOrEq(a)(b)(c)(w.zero(a["__superclass_Data.Semiring.Semiring_0"]()))})(c)}}};
a.length=function(a){return c.length(a)};a.mkPoly=I;a.move=function(a){return function(b){return function(c){return p.map(G)(function(b){return n.pAddV(a)(b)(c)})(b)}}};a.origin=function(a){return function(b){return r.fromJust(r.foldlA2(e.foldableArray)(n.p2Applicative)(z.min(a))(b))}};a.points=function(a){return a};a.prunePoly=function(a){return function(c){return function(d){var f=h.Cons,g=N(d)(-1);d=h.fromFoldable(e.foldableArray)(d);f=new f(g,d);f=L(a)(c)(f);return x.bind(b.bindMaybe)(h.tail(f))(Q)}}};
a.rect=K;a.square=function(a){return function(b){return function(c){return K(c)(w.add(n.p2Semiring(a))(c)(n.p2(b)(b)))}}};a.sutherlandHodgman=J;a.uncons=function(a){return r.fromJust(c.uncons(a))};a.updateAt=function(a){return function(b){return function(d){var e=r.quot(a)(c.length(d));return r.fromJust(c.updateAt(e)(b)(d))}}};a.polyFunctor=G;a.polyFoldable=M;a.polyTraversable=H})(PS["Data.Polygon"]=PS["Data.Polygon"]||{});
(function(a){var b=PS["Linear.R2"],c=PS["Data.Polygon"],d=PS.Utils,f=PS["Control.Apply"],e=PS["Data.Maybe"],g=PS["Data.Functor"],k=PS["Data.Foldable"],h=PS["Data.Ord"],l=function(a){return function(b){return{lo:a,hi:b}}};a.bbRec=l;a.boundingBox=function(a){return function(q){q=c.points(q);return d.fromJust(f.apply(e.applyMaybe)(g.map(e.functorMaybe)(l)(d.foldlA2(k.foldableArray)(b.p2Applicative)(h.min(a))(q)))(d.foldlA2(k.foldableArray)(b.p2Applicative)(h.max(a))(q)))}}})(PS["Data.BoundingBox"]=PS["Data.BoundingBox"]||
{});
(function(a){a.getCanvasElementByIdImpl=function(a,c,d){return function(){var f=document.getElementById(a);return f&&f instanceof HTMLCanvasElement?c(f):d}};a.getContext2D=function(a){return function(){return a.getContext("2d")}};a.setCanvasWidth=function(a){return function(c){return function(){c.width=a;return c}}};a.setCanvasHeight=function(a){return function(c){return function(){c.height=a;return c}}};a.setLineWidth=function(a){return function(c){return function(){c.lineWidth=a;return c}}};a.setFillStyle=
function(a){return function(c){return function(){c.fillStyle=a;return c}}};a.setStrokeStyle=function(a){return function(c){return function(){c.strokeStyle=a;return c}}};a.beginPath=function(a){return function(){a.beginPath();return a}};a.stroke=function(a){return function(){a.stroke();return a}};a.fill=function(a){return function(){a.fill();return a}};a.lineTo=function(a){return function(c){return function(d){return function(){a.lineTo(c,d);return a}}}};a.moveTo=function(a){return function(c){return function(d){return function(){a.moveTo(c,
d);return a}}}};a.arc=function(a){return function(c){return function(){a.arc(c.x,c.y,c.r,c.start,c.end);return a}}};a.fillRect=function(a){return function(c){return function(){a.fillRect(c.x,c.y,c.w,c.h);return a}}};a.clearRect=function(a){return function(c){return function(){a.clearRect(c.x,c.y,c.w,c.h);return a}}}})(PS["Graphics.Canvas"]=PS["Graphics.Canvas"]||{});
(function(a){var b=PS["Graphics.Canvas"],c=PS["Data.Maybe"];a.getCanvasElementById=function(a){return b.getCanvasElementByIdImpl(a,c.Just.create,c.Nothing.value)};a.arc=b.arc;a.beginPath=b.beginPath;a.clearRect=b.clearRect;a.fill=b.fill;a.fillRect=b.fillRect;a.getContext2D=b.getContext2D;a.lineTo=b.lineTo;a.moveTo=b.moveTo;a.setCanvasHeight=b.setCanvasHeight;a.setCanvasWidth=b.setCanvasWidth;a.setFillStyle=b.setFillStyle;a.setLineWidth=b.setLineWidth;a.setStrokeStyle=b.setStrokeStyle;a.stroke=b.stroke})(PS["Graphics.Canvas"]=
PS["Graphics.Canvas"]||{});
(function(a){var b=PS["Linear.R2"],c=PS["Linear.Vector"],d=PS["Data.Int"],f=PS["Data.Ring"],e=PS["Data.Functor"],g=PS["Data.EuclideanRing"],k=PS["Data.Semiring"],h=function(a){var b;if(b=0>a)b=8;else{if(b)throw Error("Failed pattern match at Grid line 16, column 47 - line 16, column 76: "+[b.constructor.name]);b=0}return(8*(a/8|0)|0)-b};a.fromGrid=function(a){return function(g){return function(h){return k.add(b.p2Semiring(k.semiringNumber))(a)(c.fMulS(b.p2Functor)(k.semiringNumber)(e.map(b.p2Functor)(d.toNumber)(b.invY(f.ringInt)(h)))(g))}}};a.gridNext=
function(a){return h(a+7|0)};a.gridPrev=h;a.gridSize=8;a.toGrid=function(a){return function(h){return function(k){return b.invY(f.ringInt)(e.map(b.p2Functor)(d.round)(c.fDivS(b.p2Functor)(g.euclideanRingNumber)(f.sub(b.p2Ring(f.ringNumber))(k)(a))(h)))}}}})(PS.Grid=PS.Grid||{});
(function(a){var b=PS["Data.Show"],c=function(a){return function(c){return function(d){return function(f){return"rgba("+(b.show(b.showInt)(a)+(","+(b.show(b.showInt)(c)+(","+(b.show(b.showInt)(d)+(","+(b.show(b.showNumber)(f)+")")))))))}}}},d=function(a){return function(c){return function(d){return"rgb("+(b.show(b.showInt)(a)+(","+(b.show(b.showInt)(c)+(","+(b.show(b.showInt)(d)+")")))))}}},f={mainGrid:{style:d(0)(0)(0),width:1},subGrid:{style:d(0)(0)(0),width:.25},subGridMinZoom:.5,point:{style:d(0)(255)(0),
radius:5},edge:{style:d(0)(255)(0),width:2},invalidFaceStyle:c(255)(0)(0)(.3),drawOrigin:!0,origin:{style:d(255)(0)(0),radius:5}};a.defaultStyle=f;a.rgb=d;a.rgba=c})(PS["Editor.Style"]=PS["Editor.Style"]||{});
(function(a){var b=PS["Data.Int"],c=PS.Grid,d=PS["Linear.R2"],f=PS["Linear.Vector"],e=PS["Data.EuclideanRing"],g=function(a){return a.zoom*a.gridSize};a.fromGrid=function(a){return c.fromGrid(a.origin)(g(a))};a.mainGridSize=function(a){return a.zoom*a.gridSize*b.toNumber(c.gridSize)};a.mkView=function(a){return function(b){return{width:a,height:b,origin:f.fDivS(d.p2Functor)(e.euclideanRingNumber)(d.p2(a)(b))(2),zoom:1,gridSize:8}}};a.subGridSize=g;a.toGrid=function(a){return c.toGrid(a.origin)(g(a))}})(PS["Editor.View"]=
PS["Editor.View"]||{});(function(a){var b=function(){function a(){}a.value=new a;return a}(),c=function(){function a(){}a.value=new a;return a}(),d=function(){function a(){}a.value=new a;return a}(),f=function(){function a(){}a.value=new a;return a}(),e=[b.value,c.value,d.value,f.value];a.SUp=b;a.SRight=c;a.SDown=d;a.SLeft=f;a.allSides=e})(PS["RedEclipse.Face.Side"]=PS["RedEclipse.Face.Side"]||{});
(function(a){function b(a,b){if(!(a.view.byteLength>a.offset+b)){for(var f=2*a.view.byteLength;f<a.offset+b;)f*=2;var f=new ArrayBuffer(f),e=new Uint8Array(f),g=new Uint8Array(a.view.buffer,a.view.byteOffset,a.offset);e.set(g);a.view=new DataView(f);a.array=new Uint8Array(f)}}a.newOutput=function(){var a=new ArrayBuffer(1024);return{view:new DataView(a),array:new Uint8Array(a),offset:0}};a.putter=function(a){return function(d){return function(f){return function(e){return function(g){return function(){b(g,
d);g.view[a](g.offset,e,f);g.offset+=d}}}}}};a.putASCII=function(a){return function(d){return function(){b(d,a.length);var f=Array.from(a,function(a){return a.codePointAt(0)});d.array.set(f,d.offset);d.offset+=a.length}}}})(PS.Put=PS.Put||{});
(function(a){var b=PS.Put,c=PS["Control.Monad.Eff"],d=PS["Data.Functor"],f=PS["Control.Apply"],e=PS["Control.Applicative"],g=PS["Control.Bind"],k=b.putter("setUint8")(1)(!1),h=new d.Functor(function(a){return function(b){return function(e){return d.map(c.functorEff)(a)(b(e))}}}),l=new f.Apply(function(){return h},function(a){return function(b){return function(d){return f.apply(c.applyEff)(a(d))(b(d))}}}),g=new g.Bind(function(){return l},function(a){return function(b){return function(c){return function(){var d=
a(c)();return b(d)(c)()}}}}),n=new e.Applicative(function(){return l},function(a){return function(b){return e.pure(c.applicativeEff)(a)}}),q=b.putter("setInt32")(4)(!0),m=b.putter("setUint16")(2)(!0);a.littleEndian=!0;a.putInt32le=q;a.putWord16le=m;a.putWord8=k;a.runPut=function(a){return a};a.putFunctor=h;a.putApply=l;a.putApplicative=n;a.putBind=g;a.newOutput=b.newOutput;a.putASCII=b.putASCII})(PS.Put=PS.Put||{});
(function(a){a.Serialize=function(a){this.put=a};a.put=function(a){return a.put}})(PS.Serialize=PS.Serialize||{});
(function(a){var b=PS["Data.Int.Bits"],c=PS.Put,d=function(a){return{edge01:a,edge23:a,edge45:a,edge67:a,edge02:a,edge46:a,edge13:a,edge57:a,edge04:a,edge15:a,edge26:a,edge37:a}},f=function(a){return b.or(b.and(a.limit)(15)<<4)(b.and(a.offset)(15))},e=new PS.Serialize.Serialize(function(a){return c.putWord8(f(a))}),g={offset:0,limit:0},k=d(g);a.edges=function(a){return[a.edge01,a.edge23,a.edge45,a.edge67,a.edge02,a.edge46,a.edge13,a.edge57,a.edge04,a.edge15,a.edge26,a.edge37]};a.emptyCube=k;a.emptyEdge=
g;a.packEdge=f;a.solidEdge={offset:0,limit:8};a.uniCube=d;a.serializeEdge=e})(PS["RedEclipse.Cube"]=PS["RedEclipse.Cube"]||{});(function(a){a.trace=function(a){console.log(a);return a}})(PS.Trace=PS.Trace||{});(function(a){a.trace=PS.Trace.trace})(PS.Trace=PS.Trace||{});
(function(a){var b=PS["Control.MonadZero"],c=PS["Data.Int"],d=PS["Data.Foldable"],f=PS["Data.Traversable"],e=PS["Data.Array"],g=PS["Data.Polygon"],k=PS["Data.BoundingBox"],h=PS["Linear.R2"],l=PS["Linear.Vector"],n=PS["Linear.Epsilon"],q=PS["Data.Segment"],m=PS["Data.Maybe"],r=PS.Grid,p=PS["RedEclipse.Face.Side"],u=PS["RedEclipse.Cube"],w=PS.Utils,v=PS["Data.Ord"],z=PS.Trace,A=PS["Data.Semigroup"],t=PS["Data.Functor"],x=PS["Control.Apply"],y=PS["Data.Ring"],B=PS["Data.Eq"],E=PS["Data.Semiring"],F=
PS["Data.Boolean"],D=PS["Control.Bind"],C=function(a){return function(b){var c=a.y<b.y;if(c)return{offset:a.y,limit:b.y};if(!c)return{offset:b.y,limit:a.y};throw Error("Failed pattern match at RedEclipse.Face line 267, column 14 - line 269, column 56: "+[c.constructor.name]);}},K=function(a){return function(b){var d=t.map(h.p2Functor)(c.round)(b);b=n.approxEQ(h.p2Ring(y.ringNumber))(h.p2Epsilon(n.numberEpsilon))(b)(t.map(h.p2Functor)(c.toNumber)(d));var e=function(a){return 0<=a&&a<=r.gridSize},d=
y.sub(h.p2Ring(y.ringInt))(d)(a);if(b=b&&e(h.r2(h.p2r2)(d).x)&&e(h.r2(h.p2r2)(d).y))return new m.Just(d);if(!b)return m.Nothing.value;throw Error("Failed pattern match at RedEclipse.Face line 144, column 20 - line 146, column 35: "+[b.constructor.name]);}},L=function(a){var b=g.prunePoly(y.ringNumber)(n.numberEpsilon)(a);if(b instanceof m.Nothing)return!0;if(b instanceof m.Just){a=function(){var a=t.map(h.p2Functor)(function(a){return r.gridPrev(c.ceil(a))})(g.origin(v.ordNumber)(b.value0)),a=f.sequence(g.polyTraversable)(m.applicativeMaybe)(t.map(g.polyFunctor)(K(a))(b.value0));
return B.eq(m.eqMaybe(B.eqBoolean))(new m.Just(!0))(t.map(m.functorMaybe)(g.isConvex(y.ringInt)(n.intEpsilon))(a))}();var d=g.length(b.value0);return(3===d||4===d)&&a}throw Error("Failed pattern match at RedEclipse.Face line 76, column 3 - line 85, column 43: "+[b.constructor.name]);},G=function(a){return function(b){return function(c){if(b instanceof p.SUp){var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);d.up=c;return d}if(b instanceof p.SRight){e={};for(d in a)a.hasOwnProperty(d)&&(e[d]=
a[d]);e.right=c;return e}if(b instanceof p.SDown){e={};for(var f in a)a.hasOwnProperty(f)&&(e[f]=a[f]);e.down=c;return e}if(b instanceof p.SLeft){e={};for(var g in a)a.hasOwnProperty(g)&&(e[g]=a[g]);e.left=c;return e}throw Error("Failed pattern match at RedEclipse.Face line 249, column 1 - line 249, column 47: "+[a.constructor.name,b.constructor.name,c.constructor.name]);}}},M=function(a){return a instanceof p.SUp||a instanceof p.SDown?!0:!1},H=function(a){return function(b){var c=a.x>b.x;if(c)return{offset:r.gridSize-
a.x,limit:r.gridSize-b.x};if(!c)return{offset:r.gridSize-b.x,limit:r.gridSize-a.x};throw Error("Failed pattern match at RedEclipse.Face line 260, column 15 - line 264, column 54: "+[c.constructor.name]);}},I=function(a){return function(b){if(M(a))return H(b.value0)(b.value1);if(F.otherwise)return C(b.value0)(b.value1);throw Error("Failed pattern match at RedEclipse.Face line 255, column 1 - line 257, column 27: "+[a.constructor.name,b.constructor.name]);}},J=function(a){return function(b){if(b instanceof
p.SUp)return a.up;if(b instanceof p.SRight)return a.right;if(b instanceof p.SDown)return a.down;if(b instanceof p.SLeft)return a.left;throw Error("Failed pattern match at RedEclipse.Face line 243, column 1 - line 243, column 28: "+[a.constructor.name,b.constructor.name]);}},N=function(a){return function(b){return function(c){var d=J(a)(b);if(d instanceof m.Nothing)return new m.Just(G(a)(b)(new m.Just(c)));if(d instanceof m.Just)return m.Nothing.value;throw Error("Failed pattern match at RedEclipse.Face line 238, column 3 - line 240, column 22: "+
[d.constructor.name]);}}},O=new t.Functor(function(a){return function(b){return{up:a(b.up),right:a(b.right),down:a(b.down),left:a(b.left)}}}),P=new d.Foldable(function(a){return function(b){return function(c){return A.append(a["__superclass_Data.Semigroup.Semigroup_0"]())(b(c.up))(A.append(a["__superclass_Data.Semigroup.Semigroup_0"]())(b(c.right))(A.append(a["__superclass_Data.Semigroup.Semigroup_0"]())(b(c.down))(b(c.left))))}}},function(a){return function(b){return function(c){return a(a(a(a(b)(c.up))(c.right))(c.down))(c.left)}}},
function(a){return function(b){return function(c){return a(c.up)(a(c.right)(a(c.down)(a(c.left)(b))))}}}),Q=function(a){return{edge01:a.down,edge23:a.down,edge45:a.up,edge67:a.up,edge02:u.solidEdge,edge46:u.solidEdge,edge13:u.solidEdge,edge57:u.solidEdge,edge04:a.right,edge15:a.left,edge26:a.right,edge37:a.left}},R=function(a){return function(b){return function(c){return function(d){return{up:a,right:b,down:c,left:d}}}}},S=new f.Traversable(function(){return P},function(){return O},function(a){return function(b){return x.apply(a["__superclass_Control.Apply.Apply_0"]())(x.apply(a["__superclass_Control.Apply.Apply_0"]())(x.apply(a["__superclass_Control.Apply.Apply_0"]())(t.map(a["__superclass_Control.Apply.Apply_0"]()["__superclass_Data.Functor.Functor_0"]())(R)(b.up))(b.right))(b.down))(b.left)}},
function(a){return f.traverseDefault(S)(a)}),T=function(a){return R(a)(a)(a)(a)},U=function(a){return function(b){var c=function(a){return function(b){return v.abs(v.ordNumber)(y.ringNumber)(a(b.value0)-a(b.value1))}};if(c=c(function(a){return a.x})(a)>=c(function(a){return a.y})(a)){if(b=b.y<(b.x-a.value0.x)/(a.value1.x-a.value0.x)*(a.value1.y-a.value0.y)+a.value0.y)return p.SUp.value;if(!b)return p.SDown.value;throw Error("Failed pattern match at RedEclipse.Face line 229, column 12 - line 229, column 42: "+
[b.constructor.name]);}if(!c){if(b=b.x<(b.y-a.value0.y)/(a.value1.y-a.value0.y)*(a.value1.x-a.value0.x)+a.value0.x)return p.SRight.value;if(!b)return p.SLeft.value;throw Error("Failed pattern match at RedEclipse.Face line 232, column 12 - line 232, column 45: "+[b.constructor.name]);}throw Error("Failed pattern match at RedEclipse.Face line 226, column 3 - line 232, column 45: "+[c.constructor.name]);}},X=function(a){return function(b){return function(d){if(b instanceof m.Nothing)return m.Nothing.value;
if(b instanceof m.Just){var f=w.fromJust(e.head(e.difference(h.p2Eq(B.eqInt))(a)([d.value0,d.value1]))),f=U(t.map(q.functorSeg)(function(a){return t.map(h.p2Functor)(c.toNumber)(a)})(d))(t.map(h.p2Functor)(c.toNumber)(f));return N(b.value0)(f)(d)}throw Error("Failed pattern match at RedEclipse.Face line 196, column 1 - line 196, column 31: "+[a.constructor.name,b.constructor.name,d.constructor.name]);}}},V=function(a){if(a.up instanceof m.Nothing&&a.left instanceof m.Just&&a.right instanceof m.Just){var b=
w.fromJust(e.head(e.intersect(h.p2Eq(B.eqInt))([a.left.value0.value0,a.left.value0.value1])([a.right.value0.value0,a.right.value0.value1]))),c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c.up=new m.Just(new q.Seg(b,b));return c}if(a.right instanceof m.Nothing&&a.up instanceof m.Just&&a.down instanceof m.Just){b=w.fromJust(e.head(e.intersect(h.p2Eq(B.eqInt))([a.up.value0.value0,a.up.value0.value1])([a.down.value0.value0,a.down.value0.value1])));d={};for(c in a)a.hasOwnProperty(c)&&(d[c]=a[c]);
d.right=new m.Just(new q.Seg(b,b));return d}if(a.down instanceof m.Nothing&&a.left instanceof m.Just&&a.right instanceof m.Just){b=w.fromJust(e.head(e.intersect(h.p2Eq(B.eqInt))([a.left.value0.value0,a.left.value0.value1])([a.right.value0.value0,a.right.value0.value1])));d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=a[f]);d.down=new m.Just(new q.Seg(b,b));return d}if(a.left instanceof m.Nothing&&a.up instanceof m.Just&&a.down instanceof m.Just){b=w.fromJust(e.head(e.intersect(h.p2Eq(B.eqInt))([a.up.value0.value0,
a.up.value0.value1])([a.down.value0.value0,a.down.value0.value1])));d={};for(var g in a)a.hasOwnProperty(g)&&(d[g]=a[g]);d.left=new m.Just(new q.Seg(b,b));return d}return a},W=function(a){var e=g.length(a);return D.bind(m.bindMaybe)(b.guard(m.monadZeroMaybe)(3===e||4===e))(function(){var k=t.map(h.p2Functor)(function(a){return r.gridPrev(c.ceil(a))})(g.origin(v.ordNumber)(a));return D.bind(m.bindMaybe)(f.sequence(g.polyTraversable)(m.applicativeMaybe)(t.map(g.polyFunctor)(K(k))(a)))(function(a){return D.bind(m.bindMaybe)(b.guard(m.monadZeroMaybe)(g.isConvex(y.ringInt)(n.intEpsilon)(a)))(function(){var b=
g.edges(a),c=g.points(a);return D.bind(m.bindMaybe)(d.foldl(d.foldableArray)(X(c))(m.Just.create(T(m.Nothing.value)))(b))(function(a){var b=function(){var b=3===e;if(b)return V(a);if(!b)return a;throw Error("Failed pattern match at RedEclipse.Face line 191, column 15 - line 191, column 59: "+[b.constructor.name]);}(),c=d.foldl(d.foldableArray)(function(a){return function(c){return G(a)(c)(t.map(m.functorMaybe)(I(c))(J(b)(c)))}})(T(m.Nothing.value))(p.allSides);return f.sequence(S)(m.applicativeMaybe)(c)})})})})};
a.addMissing=V;a.assignSide=U;a.face=R;a.faceToCube=Q;a.getSide=J;a.horiz=H;a.isHoriz=M;a.polyToFace=W;a.segToEdge=I;a.setEdge=N;a.setSide=G;a.toFaceCoords=K;a.toPlane=function(a){var b=k.boundingBox(v.ordInt)(a),d=t.map(h.p2Functor)(r.gridNext)(b.hi),d=h.r2(h.p2r2)(d),b=t.map(h.p2Functor)(r.gridPrev)(b.lo),b=h.r2(h.p2r2)(b),p=d.y-b.y;a=g.move(E.semiringInt)(a)(y.negate(h.v2Ring(y.ringInt))(b));var q=t.map(g.polyFunctor)(t.map(h.p2Functor)(c.toNumber))(a),C=d.x-b.x;a=f.sequence(f.traversableArray)(m.applicativeMaybe)(t.mapFlipped(t.functorArray)(e.range(0)((C/
r.gridSize|0)-1))(function(a){return f.sequence(f.traversableArray)(m.applicativeMaybe)(t.mapFlipped(t.functorArray)(e.range(0)((p/r.gridSize|0)-1))(function(b){b=g.square(E.semiringNumber)(c.toNumber(r.gridSize))(t.map(h.p2Functor)(c.toNumber)(l.fMulS(h.p2Functor)(E.semiringInt)(h.p2(z.trace(a))(z.trace(b)))(r.gridSize)));b=D.bind(m.bindMaybe)(g.clip(b)(q))(g.prunePoly(y.ringNumber)(n.numberEpsilon));if(b instanceof m.Nothing)return new m.Just(u.emptyCube);if(b instanceof m.Just)return z.trace(t.map(m.functorMaybe)(Q)(W(z.trace(b.value0))));
throw Error("Failed pattern match at RedEclipse.Face line 127, column 17 - line 129, column 80: "+[b.constructor.name]);}))}));return t.map(m.functorMaybe)(function(a){return{size:h.v2(C/r.gridSize|0)(p/r.gridSize|0),plane:a}})(a)};a.uniFace=T;a.validFace=L;a.validatePoly=function(a){var b=k.boundingBox(v.ordInt)(a),d=t.map(h.p2Functor)(r.gridNext)(b.hi),f=h.r2(h.p2r2)(d),b=t.map(h.p2Functor)(r.gridPrev)(b.lo),n=h.r2(h.p2r2)(b),p=f.y-n.y;a=g.move(E.semiringInt)(a)(y.negate(h.v2Ring(y.ringInt))(n));
var q=t.map(g.polyFunctor)(t.map(h.p2Functor)(c.toNumber))(a),C=f.x-n.x,f=t.mapFlipped(t.functorArray)(e.range(0)((p/r.gridSize|0)-1))(function(a){return t.mapFlipped(t.functorArray)(e.range(0)((C/r.gridSize|0)-1))(function(b){b=g.square(E.semiringNumber)(c.toNumber(r.gridSize))(t.map(h.p2Functor)(c.toNumber)(l.fMulS(h.p2Functor)(E.semiringInt)(h.p2(b)(a))(r.gridSize)));return m.maybe(!0)(L)(g.clip(b)(q))})});return{lo:b,hi:d,validity:f}};a.vert=C;a.functorFace=O;a.foldableFace=P;a.traversableFace=
S})(PS["RedEclipse.Face"]=PS["RedEclipse.Face"]||{});(function(a){var b=PS["Data.Maybe"],c=PS["RedEclipse.Face"];a.mkWorkArea=function(a){return{poly:a,point:b.Nothing.value,validity:c.validatePoly(a)}}})(PS["Editor.WorkArea"]=PS["Editor.WorkArea"]||{});
(function(a){var b=PS["Editor.Style"],c=PS["Editor.View"],d=PS["Editor.WorkArea"];a.mkEditor=function(a){return function(e){return function(g){return function(k){return{context:a,style:b.defaultStyle,view:c.mkView(e)(g),workArea:d.mkWorkArea(k)}}}}}})(PS["Editor.Editor"]=PS["Editor.Editor"]||{});
(function(a){var b=PS["Data.Maybe"],c=PS["Data.Maybe.First"],d=PS["Data.Foldable"],f=PS["Linear.R2"],e=PS["Linear.Metric"],g=PS["Data.Polygon"],k=PS["Data.Segment"],h=PS["Editor.View"],l=PS["Editor.WorkArea"],n=PS["Linear.Epsilon"],q=PS.Utils,m=PS["Data.Ring"],r=PS["Data.Traversable"],p=PS["Data.Semigroup"],u=PS["Data.Functor"],w=PS["Control.Bind"],v=PS["Control.Applicative"],z=function(a){return function(b){return function(c){var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);d.workArea=l.mkWorkArea(b(c));
return d}}},A=function(a){return function(h){return function(l){var E=function(a){return b.fromMaybe(a)(g.prunePoly(m.ringNumber)(n.numberEpsilon)(a))},t=function(c){var d=e.distance(f.p2Metric)(l)(c.elem.value1)<a;if(d)return new b.Just({point:{before:c.elem.value0,point:l,after:c.elem.value2},finish:function(a){return E(g.updateAt(c.idx+1|0)(a)(h))}});if(!d)return b.Nothing.value;throw Error("Failed pattern match at Drag.EditPoint line 33, column 7 - line 36, column 22: "+[d.constructor.name]);
},D=d.foldMap(d.foldableArray)(c.monoidFirst)(function(a){return c.First(t(a))})(q.enumerate(r.traversableArray)(g.corners(h))),C=function(c){var d=k.distance(l)(c.elem)<a;if(d)return new b.Just({point:{before:c.elem.value0,point:l,after:c.elem.value1},finish:function(a){return E(g.insertAt(c.idx+1|0)(a)(h))}});if(!d)return b.Nothing.value;throw Error("Failed pattern match at Drag.EditPoint line 38, column 7 - line 41, column 22: "+[d.constructor.name]);},z=d.foldMap(d.foldableArray)(c.monoidFirst)(function(a){return c.First(C(a))})(q.enumerate(r.traversableArray)(g.edges(h)));
return c.runFirst(p.append(c.semigroupFirst)(D)(z))}}},t=function(a){return function(c){var d=h.toGrid(a.view);if(a.workArea.point instanceof b.Nothing)return a;if(a.workArea.point instanceof b.Just){var e={},f;for(f in a)a.hasOwnProperty(f)&&(e[f]=a[f]);f={};for(var g in a.workArea)a.workArea.hasOwnProperty(g)&&(f[g]=a.workArea[g]);g=b.Just;var k={},l;for(l in a.workArea.point.value0)a.workArea.point.value0.hasOwnProperty(l)&&(k[l]=a.workArea.point.value0[l]);k.point=d(c);f.point=new g(k);e.workArea=
f;return e}throw Error("Failed pattern match at Drag.EditPoint line 58, column 3 - line 60, column 99: "+[a.workArea.point.constructor.name]);}};a.editPointDrag=function(a){return function(c){var d=h.toGrid(a.view),e=u.map(g.polyFunctor)(h.fromGrid(a.view))(a.workArea.poly);return w.bind(b.bindMaybe)(A(a.style.point.radius)(e)(c))(function(c){var e={before:d(c.point.before),point:d(c.point.point),after:d(c.point.after)},f=function(){var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);d={};for(var f in a.workArea)a.workArea.hasOwnProperty(f)&&
(d[f]=a.workArea[f]);d.point=new b.Just(e);c.workArea=d;return c}();return v.pure(b.applicativeMaybe)({move:t(f),stop:z(f)(function(a){return u.map(g.polyFunctor)(d)(c.finish(a))})})})}};a.moveEdit=t;a.onPoly=A;a.stopEdit=z})(PS["Drag.EditPoint"]=PS["Drag.EditPoint"]||{});
(function(a){var b=PS["Data.Maybe"],c=PS["Linear.R2"],d=PS["Data.Semiring"],f=PS["Data.Ring"],e=function(a){return function(b){var e={},f;for(f in a)a.hasOwnProperty(f)&&(e[f]=a[f]);f={};for(var n in a.view)a.view.hasOwnProperty(n)&&(f[n]=a.view[n]);f.origin=d.add(c.p2Semiring(d.semiringNumber))(a.view.origin)(b);e.view=f;return e}};a.scroll=e;a.scrollDrag=function(a){return function(d){var h=function(b){return e(a)(f.sub(c.p2Ring(f.ringNumber))(b)(d))};return new b.Just({move:h,stop:h})}}})(PS["Drag.Scroll"]=
PS["Drag.Scroll"]||{});
(function(a){var b=PS["Control.Monad.Eff"],c=PS.Math,d=PS["Data.Int"],f=PS["Data.Traversable"],e=PS["Data.Maybe"],g=PS["Graphics.Canvas"],k=PS["Linear.R2"],h=PS["Linear.Vector"],l=PS["Data.Polygon"],n=PS["Editor.View"],q=PS.Utils,m=PS["Data.Foldable"],r=PS["Control.Applicative"],p=PS["Data.Functor"],u=PS["Data.Semiring"],w=PS["Data.Ring"],v=PS["Data.EuclideanRing"],z=PS["Data.Unit"],A=function(a){return function(c){return function(e){return function(h){return function(k){return m.for_(b.applicativeEff)(m.foldableArray)(q.enumerate(f.traversableArray)(e))(function(e){return m.for_(b.applicativeEff)(m.foldableArray)(q.enumerate(f.traversableArray)(e.elem))(function(f){return r.unless(b.applicativeEff)(f.elem)(p["void"](b.functorEff)(function(){g.setFillStyle(a)(k)();return g.fillRect(k)({x:c.x+
d.toNumber(f.idx)*h,y:c.y+d.toNumber(-e.idx)*h,w:h,h:-h})()}))})})}}}}},t=function(a){return function(d){return function(e){var f={x:d.x,y:d.y,r:a.radius,start:0,end:2*c.pi};return p["void"](b.functorEff)(function(){g.beginPath(e)();g.setFillStyle(a.style)(e)();g.arc(e)(f)();return g.fill(e)()})}}},x=function(a){return function(c){return function(d){return function(e){var f=l.uncons(d),h=k.r2(k.p2r2)(f.head);return function(){g.beginPath(e)();g.setStrokeStyle(a.style)(e)();g.setLineWidth(a.width)(e)();
g.moveTo(e)(h.x)(h.y)();m.for_(b.applicativeEff)(m.foldableArray)(f.tail)(function(a){return g.lineTo(e)(a.x)(a.y)})();g.lineTo(e)(h.x)(h.y)();g.stroke(e)();return m.for_(b.applicativeEff)(m.foldableArray)(l.points(d))(function(a){return t(c)(a)(e)})()}}}}},y=function(a){return function(c){return function(e){return function(f){var l=k.r2(k.p2r2)(w.sub(k.p2Ring(w.ringNumber))(c.origin)(h.fMulS(k.p2Functor)(u.semiringNumber)(p.map(k.p2Functor)(function(a){return d.toNumber(d.round(a))})(h.fDivS(k.p2Functor)(v.euclideanRingNumber)(c.origin)(e)))(e)));
return p["void"](b.functorEff)(function(){g.beginPath(f)();g.setStrokeStyle(a.style)(f)();g.setLineWidth(a.width)(f)();q.whileM_(b.monadEff)(l.x)(function(a){return a<=c.width})(function(a){return function(){g.moveTo(f)(a)(0)();g.lineTo(f)(a)(c.height)();return a+e}})();q.whileM_(b.monadEff)(l.y)(function(a){return a<=c.height})(function(a){return function(){g.moveTo(f)(0)(a)();g.lineTo(f)(c.width)(a)();return a+e}})();return g.stroke(f)()})}}}},B=function(a){return function(b){return function(c){return function(d){return function(){g.beginPath(d)();
g.setStrokeStyle(a.style)(d)();g.setLineWidth(a.width)(d)();g.moveTo(d)(c.before.x)(c.before.y)();g.lineTo(d)(c.point.x)(c.point.y)();g.lineTo(d)(c.after.x)(c.after.y)();g.stroke(d)();return t(b)(c.point)(d)()}}}}};a.drawEditPoint=B;a.drawGrid=y;a.drawPoint=t;a.drawPoly=x;a.drawValidity=A;a.drawWorkArea=function(a){var c=n.subGridSize(a.view),d=n.mainGridSize(a.view),f=n.fromGrid(a.view),h=p.map(l.polyFunctor)(f)(a.workArea.poly);return function(){g.clearRect(a.context)({x:0,y:0,w:a.view.width,h:a.view.height})();
r.when(b.applicativeEff)(a.view.zoom>a.style.subGridMinZoom)(y(a.style.subGrid)(a.view)(c)(a.context))();y(a.style.mainGrid)(a.view)(d)(a.context)();r.when(b.applicativeEff)(a.style.drawOrigin)(t(a.style.origin)(a.view.origin)(a.context))();A(a.style.invalidFaceStyle)(f(a.workArea.validity.lo))(a.workArea.validity.validity)(d)(a.context)();x(a.style.edge)(a.style.point)(h)(a.context)();if(a.workArea.point instanceof e.Nothing)return z.unit;if(a.workArea.point instanceof e.Just)return B(a.style.edge)(a.style.point)({before:f(a.workArea.point.value0.before),
point:f(a.workArea.point.value0.point),after:f(a.workArea.point.value0.after)})(a.context)();throw Error("Failed pattern match at Editor.Render line 95, column 3 - line 99, column 86: "+[a.workArea.point.constructor.name]);}}})(PS["Editor.Render"]=PS["Editor.Render"]||{});
(function(a){a.saveAsFile=function(a){return function(c){return function(){var d;d=c.array;var f=c.offset;d=d.byteLength===f?d:d.subarray(0,f);d=pako.gzip(d);d=new Blob([d],{type:"application/obr"});window.navigator.msSaveOrOpenBlob?window.navigator.msSaveBlob(d,a):(f=window.document.createElement("a"),f.href=window.URL.createObjectURL(d),f.download=a,document.body.appendChild(f),f.click(),document.body.removeChild(f))}}}})(PS.Interactive=PS.Interactive||{});
(function(a){a.clientX=function(a){return function(){return a.clientX}};a.clientY=function(a){return function(){return a.clientY}}})(PS.JQuery=PS.JQuery||{});(function(a){var b=PS.JQuery;a.clientX=b.clientX;a.clientY=b.clientY})(PS.JQuery=PS.JQuery||{});
(function(a){var b=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),c=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}();a.Leaf=b;a.Node=c;a.children=function(a){if(a instanceof b)return[];if(a instanceof c)return[a.value0.sed,a.value0.swd,a.value0.ned,a.value0.nwd,a.value0.seu,a.value0.swu,a.value0.neu,a.value0.nwu];throw Error("Failed pattern match at RedEclipse.Octree line 20, column 1 - line 20, column 23: "+[a.constructor.name]);
}})(PS["RedEclipse.Octree"]=PS["RedEclipse.Octree"]||{});(function(a){var b=PS.Put,c=b.putWord16le,d=b.putASCII;a.putMapzInt=b.putInt32le;a.putMapzString=d;a.putMapzUShort=c})(PS["RedEclipse.Types"]=PS["RedEclipse.Types"]||{});
(function(a){var b=PS["Control.Apply"],c=PS["Control.Bind"],d=PS.Serialize,f=PS.Put,e=PS["RedEclipse.Types"],g=PS["RedEclipse.Cube"],k=PS["RedEclipse.Octree"],h=PS.Utils,l=PS["Data.Foldable"],n=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),q=new d.Serialize(function(a){var m=function(a){return a instanceof k.Leaf?c.bind(f.putBind)(e.putMapzUShort(0))(function(){return c.bind(f.putBind)(l.traverse_(f.putApplicative)(l.foldableArray)(d.put(g.serializeEdge))(g.edges(a.value0)))(function(){return h.replicateA_(f.putApplicative)(6)(e.putMapzUShort(1))})}):
b.applySecond(f.putApply)(f.putWord8(255))(l.traverse_(f.putApplicative)(l.foldableArray)(m)(k.children(a)))};return l.traverse_(f.putApplicative)(l.foldableArray)(m)(a)}),m=new d.Serialize(function(a){return c.bind(f.putBind)(e.putMapzString(a.value0.magic))(function(){return e.putMapzInt(a.value0.version)})}),r=new d.Serialize(function(a){return l.traverse_(f.putApplicative)(l.foldableArray)(e.putMapzInt)([a.x,a.y,a.z])}),p=new d.Serialize(function(a){return c.bind(f.putBind)(d.put(r)(a.orients))(function(){return c.bind(f.putBind)(d.put(r)(a.sizes))(function(){return c.bind(f.putBind)(e.putMapzInt(a.grid))(function(){return e.putMapzInt(a.orient)})})})}),
u=new d.Serialize(function(a){return c.bind(f.putBind)(d.put(p)(a.header))(function(){return d.put(q)(a.geom)})}),w=new d.Serialize(function(a){return c.bind(f.putBind)(d.put(m)(a.header))(function(){return d.put(u)(a.prefab)})}),v=new n({magic:"OEBR",version:0});a.PrefabFileHeader=n;a.PrefabGeom=function(a){return a};a.defaultPrefabFileHeader=v;a.mapzIVec3=function(a){return function(b){return function(c){return{x:a,y:b,z:c}}}};a.serializeMpaIVec3=r;a.serializePrefabFileHeader=m;a.serializePrefabHeader=
p;a.serializePrefabGeom=q;a.serializePrefab=u;a.serializePrefabFile=w})(PS["RedEclipse.Prefab"]=PS["RedEclipse.Prefab"]||{});
(function(a){var b=PS.Interactive,c=PS["Data.Array"],d=PS["Data.Maybe"],f=PS["Data.Maybe.First"],e=PS["Control.Monad.Eff"],g=PS["Control.Monad.Eff.Ref"],k=PS["Control.Monad.Eff.Console"],h=PS["Control.Monad.Eff.JQuery"],l=PS.JQuery,n=PS["Data.Foreign"],q=PS["Data.Either"],m=PS["Data.Int"],r=PS["Data.Bifunctor"],p=PS["Linear.R2"],u=PS["Editor.Render"],w=PS["Drag.Scroll"],v=PS["Drag.EditPoint"],z=PS.Put,A=PS.Serialize,t=PS["RedEclipse.Octree"],x=PS["RedEclipse.Prefab"],y=PS["RedEclipse.Face"],B=PS.Trace,
E=PS["Control.Bind"],F=PS["Data.Functor"],D=PS["Data.Show"],C=PS["Control.Apply"],K=PS["Data.Semigroup"],L=PS["Data.Unit"],G=function(a){return function(b){return function(c){return function(d){var e;if(a)e=.1;else{if(a)throw Error("Failed pattern match at Interactive line 114, column 16 - line 116, column 1: "+[a.constructor.name]);e=-.1}return function(){h.preventDefault(c)();var a=g["modifyRef'"](b)(function(a){var b=a.editor.view.zoom+e;var c=.2<=b;if(c){var c={},d;for(d in a)a.hasOwnProperty(d)&&
(c[d]=a[d]);d={};for(var f in a.editor)a.editor.hasOwnProperty(f)&&(d[f]=a.editor[f]);f={};for(var g in a.editor.view)a.editor.view.hasOwnProperty(g)&&(f[g]=a.editor.view[g]);f.zoom=b;d.view=f;c.editor=d;a=c}else if(c)throw Error("Failed pattern match at Interactive line 109, column 14 - line 111, column 23: "+[c.constructor.name]);return{state:a,value:a.editor}})();return u.drawWorkArea(a)()}}}}},M=function(a){return function(f){return function(l){return function(){h.preventDefault(f)();var l=h.select("#depth input")(),
l=F.map(e.functorEff)(n.readString)(h.getValue(l))(),u=E.bind(q.bindEither)(r.lmap(q.bifunctorEither)(D.show(n.showForeignError))(l))(function(a){return d.maybe(new q.Left("Not Int"))(q.Right.create)(m.fromString(a))});if(u instanceof q.Left)return k.log(u.value0)();if(u instanceof q.Right){l=g.readRef(a)();l=y.toPlane(l.editor.workArea.poly);if(l instanceof d.Nothing)return k.log("Invalid polygon")();if(l instanceof d.Just){var w=x.PrefabGeom(F.map(F.functorArray)(t.Leaf.create)(c.concatMap(function(a){return c.concatMap(function(a){return F.map(F.functorArray)(function(b){return a})(c.range(1)(u.value0))})(a)})(B.trace(l.value0.plane)))),
l={header:{orients:x.mapzIVec3(0)(0)(0),sizes:x.mapzIVec3(p.r2(p.v2r2)(l.value0.size).x)(u.value0)(p.r2(p.v2r2)(l.value0.size).y),grid:8,orient:1},geom:w},l={header:x.defaultPrefabFileHeader,prefab:l},w=z.newOutput();z.runPut(A.put(x.serializePrefabFile)(l))(w)();return b.saveAsFile("prefab.obr")(w)()}throw Error("Failed pattern match at Interactive line 140, column 7 - line 155, column 41: "+[l.constructor.name]);}throw Error("Failed pattern match at Interactive line 134, column 3 - line 155, column 41: "+
[u.constructor.name]);}}}},H=function(a){return C.apply(e.applyEff)(F.map(e.functorEff)(p.p2)(l.clientX(a)))(l.clientY(a))},I=function(a){return function(b){return function(c){return F["void"](e.functorEff)(function(){var c=H(b)();return g.modifyRef(a)(function(a){var b={},d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);b.drag=f.runFirst(K.append(f.semigroupFirst)(v.editPointDrag(a.editor)(c))(w.scrollDrag(a.editor)(c)));return b})()})}}},J=function(a){return function(b){return function(c){return function(){var c=
g.readRef(a)(),e=H(b)();if(c.drag instanceof d.Nothing)return L.unit;if(c.drag instanceof d.Just)return u.drawWorkArea(c.drag.value0.move(e))();throw Error("Failed pattern match at Interactive line 72, column 3 - line 74, column 50: "+[c.drag.constructor.name]);}}}},N=function(a){return function(b){return function(c){return function(){var c=H(b)(),e=g["modifyRef'"](a)(function(a){if(!(a.drag instanceof d.Nothing))if(a.drag instanceof d.Just)a={drag:d.Nothing.value,editor:a.drag.value0.stop(c)};else throw Error("Failed pattern match at Interactive line 88, column 14 - line 91, column 58: "+
[a.drag.constructor.name]);return{state:a,value:a.editor}})();return u.drawWorkArea(e)()}}}};a.mouseXY=H;a.onMouseDown=I;a.onMouseMove=J;a.onMouseUp=N;a.onSave=M;a.onZoom=G;a.setUpHandlers=function(a){return function(){var b=g.newRef({drag:d.Nothing.value,editor:a})(),c=h.select("#work-area")();h.on("mousedown")(I(b))(c)();h.on("mousemove")(J(b))(c)();h.on("mouseup")(N(b))(c)();c=h.select("#zoom-in")();h.on("click")(G(!0)(b))(c)();c=h.select("#zoom-out")();h.on("click")(G(!1)(b))(c)();c=h.select("#save")();
return h.on("click")(M(b))(c)()}}})(PS.Interactive=PS.Interactive||{});
(function(a){var b=PS["Control.Monad.Eff"],c=PS["Control.Monad.Eff.Console"],d=PS["DOM.HTML"],f=PS["DOM.HTML.Window"],e=PS["Data.Int"],g=PS["Data.Maybe"],k=PS["Editor.Editor"],h=PS["Editor.Render"],l=PS["Graphics.Canvas"],n=PS.Interactive,q=PS["Linear.R2"],m=PS["Data.Functor"],r=PS["Data.Show"],p=PS.Utils.fromJust(PS["Data.Polygon"].mkPoly([q.p2(0)(2),q.p2(16)(0),q.p2(8)(8),q.p2(-1)(16)]));a.main=function(){var a=d.window(),q=m.map(b.functorEff)(e.toNumber)(f.innerWidth(a))(),a=m.map(b.functorEff)(e.toNumber)(f.innerHeight(a))(),
v=l.getCanvasElementById("work-area")();if(v instanceof g.Nothing)return c.log("Failed to find #work-area")();if(v instanceof g.Just)return l.setCanvasWidth(q)(v.value0)(),l.setCanvasHeight(a)(v.value0)(),v=l.getContext2D(v.value0)(),c.log("Found #work-area and set width = "+(r.show(r.showNumber)(q)+(", height = "+r.show(r.showNumber)(a))))(),q=k.mkEditor(v)(q)(a)(p),h.drawWorkArea(q)(),n.setUpHandlers(q)();throw Error("Failed pattern match at Main line 44, column 3 - line 53, column 21: "+[v.constructor.name]);
};a.poly=p})(PS.Main=PS.Main||{});PS.Main.main();
